### ISSUE TITLE
Create a Vcpkg

### ISSUE THREAD

**Issue by bangusi** [Azure/azure-storage-cpp#105]
This is a feature request. 
Since there is already a Vcpkg for cpprestsdk the port should be painless.

**Comment by JasonYang-MSFT** [comment]
@bangusi Great to hear your feature request. We have been already considering to port to Vcpkg. It is still under discussion. Hope we can resolve all the issues and onboard Vcpkg soon.

**Comment by JasonYang-MSFT** [comment]
Hi, @bangusi 

Thanks a lot for your advice. Now we have onboard vcpkg. Please try it out if you want https://github.com/Microsoft/vcpkg/tree/master/ports/azure-storage-cpp.

For those existing projects, you might need to add $(VcpkgRoot)include to "Additional include directories".

**Comment by bangusi** [comment]
I was able to build dynamic but static build failed.
This is my first attempt to build the library so I don't have any existing azure-storage-cpp projects ( from nugget)
These are the errors from static build:
~~~~
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: E:/CMake/bin/cmake.exe;--build;.;--config;Release;--target;i
nstall;--;/m
    Working Directory: D:/vcpkg/buildtrees/azure-storage-cpp/x64-windows-static-
rel
    See logs for more information:
      D:\vcpkg\buildtrees\azure-storage-cpp\package-x64-windows-static-rel-out.l
og
      D:\vcpkg\buildtrees\azure-storage-cpp\package-x64-windows-static-rel-err.l
og

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:3 (vcpkg_execute_required_process)
  ports/azure-storage-cpp/portfile.cmake:24 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)


Error: building package azure-storage-cpp:x64-windows-static failed

~~~~

**Comment by JasonYang-MSFT** [comment]
Hi @bangusi,

This is an known issue. We released in Dynamic Link Library in the past. So we first on board vcpkg with build dynamic. Gonna to fix it soon.
