### ISSUE TITLE
pplx tasks fail to end

### ISSUE THREAD

**Issue by shlomiapel** [Azure/azure-storage-cpp#108]
Hi,

i am encountering again a problem similar to issue #83 .
i am tracking tasks which are pending to complete. i have an environment where tasks working on block blobs get stuck and do no return. most of the operations done by my client are on block blobs so this should not indicate that the problem only appears on block blobs.

Taking a specific PUT request which appeared to be stuck, 
i looked at the blob logs of the storage account and saw that the request does not appear in the logs.
all other requests appear as Success.

the code again is the same as appears in #83.
i am now using azure build 2.5.0 and casablanca 2.9.1.

**Comment by JasonYang-MSFT** [comment]
Hi @shlomiapel ,

I will look into issue. But for that, I want more info about this issue.
1. Does it happen in uploading? I noticed you take PUT request.
2. Can you provide the account name and the client request id used for the failed request?
3. As you mentioned, the request does not appear in the logs, does it mean request is not sent?
4. Does it still hang at `  auto whenAllDone = pplx::when_all(tasks.begin(), tasks.end());`?

**Comment by shlomiapel** [comment]
Hi @JasonYang-MSFT 
1. It happens during list and delete blob operations as well.
2. https://azurezcasa9468.blob.core.windows.net/journal/6e22c18c-3434-4f27-bc94-383d3e0e9ded/19b502c1-1046-4a60-b2d5-7b53dd0c2720/Debian_FO001_1/a24b_log-349-History_JRN_190000_7c_1_553d
3. i am not sure it was sent sent but this is my assumption.
4. yes.

**Comment by hachling** [comment]
Hi @JasonYang-MSFT 
any update on this? This has reproduced in our lab 3 times so far.
it probably happens when there are bad network conditions, but i am not certain this is related.

**Comment by JasonYang-MSFT** [comment]
Hi @hachling,

I didn't repro this issue in local. Can you share a dump of the stack to identify the root cause?

**Comment by shlomiapel** [comment]
How do i collect a dump of the stack? simply collect the core dump of the process?

**Comment by JasonYang-MSFT** [comment]
The core dump of the process will work too.

**Comment by achie-liang** [comment]
@shlomiapel 
Regarding  to current investigation this is more likely an issue related to windows server.
Please continue the investigation from windows server perspective and feel free to contact us for any questions/issues about the SDK.
