### ISSUE TITLE
Feedback Request: How about replace libxml++ with libxml2?

### ISSUE THREAD

**Issue by JasonYang-MSFT** [Azure/azure-storage-cpp#109]
Hi Everyone,

This is a discussion thread on replacing libxml++ with libxml2.

Recently we received several requests to link this library in static. But libxml++ with LGPL License make it controversial. So we came up an idea of replacing libxml++ with libxml2 while `libxml++ is a C++ wrapper for the libxml XML parser library. `

What's your opinion? we want see the potential impact to every one before replacing it.

**Comment by jasonzio** [comment]
I'd be quite happy to see this. My application already made this switch (to using libxml2 with a home-grown C++ wrapper), and it would reduce my runtime footprint to not also need libxml++.

**Comment by jduo** [comment]
It's actually a bigger problem than the LGPL dependency that libxml++ has. It introduces a dependency on gettext, which has a GPL licence.

**Comment by katmsft** [comment]
libxml++ is removed in release 4.0.0. Feel free to try it out!
