### ISSUE TITLE
Azure Storage C++ SDK (wastorage) does not work with v141 toolset 

### ISSUE THREAD

**Issue by adamw86** [Azure/azure-storage-cpp#112]
This issue breaks both builds and intellisense for C++ projects.  Robert Schumacher (MSFT) has fixed this issue in the CppREST SDK and can provide guidance here on a fix.

The issue is that the include paths are not being properly set up during installation of the Azure Storage package.

**Comment by achie-liang** [comment]
@adamw86 
This issue has been fixed in release 3.0.0. Feel free to try and provide your feedback.
