### ISSUE TITLE
MFC/ATL projects unable to build with Azure Storage SDK (wastorage)

### ISSUE THREAD

**Issue by adamw86** [Azure/azure-storage-cpp#113]
MFC/ATL projects use Windows.h which defines max/min macros.  std::max and std::min are used in d Azure SDK leading to a conflict that breaks build.  Robert Schumacher has suggested we solve this in conflict using one of the following solutions
i.	Push/pop macros [preferable]
ii.	Using std::max [more of a hack but works]

A current workaround is to #undef max and #undef min in these projects so they can build and consume Azure SDK.  We tested this in an MFC project and it built fine.

**Comment by achie-liang** [comment]
@adamw86 
This issue has been fixed in release 3.0.0. Feel free to try and provide your feedback.
