### ISSUE TITLE
azure-storage-cpp go to use it in QT

### ISSUE THREAD

**Issue by Omgan** [Azure/azure-storage-cpp#114]
Is there a support for using this library in QT??

**Comment by JasonYang-MSFT** [comment]
We haven't verified this case, but this should work for QT.

**Comment by QuentinCG** [comment]
If you only need to download/upload/list blobs (files) from/to azure storage containers, you maybe don't need to use `azure-storage-cpp` library.

You could use this class (with only Qt5+ as dependency):
https://github.com/QuentinCG/QAzureStorageRestApi
