### ISSUE TITLE
undefined reference to `azure::storage::cloud_blob_client::get_container_reference(std::string)

### ISSUE THREAD

**Issue by garethblock** [Azure/azure-storage-cpp#119]
Hello,

I have built the library but am having a trouble when trying to use any function that takes a string_t. I'm getting:

```
testCpp/d5xdhpiaz0ugo43hs4g0p9nsf/main.o: In function `main':
src/main/test/main.cpp:274: undefined reference to `azure::storage::cloud_storage_account::parse(std::string const&)'
src/main/test/main.cpp:278: undefined reference to `azure::storage::cloud_blob_client::get_container_reference(std::string) const'
src/main/test/main.cpp:288: undefined reference to `azure::storage::cloud_blob_container::get_block_blob_reference(std::string) const'
```

**Comment by JasonYang-MSFT** [comment]
You may need add -L<path to libazurestorage.so> -lazurestorage in your build command.

**Comment by garethblock** [comment]
@JasonYang-MSFT That is included in my build command. The problem is if any function uses the utility::string_t, it somehow converts it to a std::string. I know that the utlity::string_t is typedef'd to std::string but the function is expecting a utility::string_t and not a std::string. When I try passing a utility::string_t, I get the error above.

**Comment by JasonYang-MSFT** [comment]
Hi @garethblock ,

Can you share the OS version and compiler version?

Thanks,
-Jason

**Comment by garethblock** [comment]
@JasonYang-MSFT 

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

moe@moe:~$ g++ -v --version
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

moe@moe:~$ g++-4.8 -v --version
Using built-in specs.
COLLECT_GCC=g++-4.8
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
g++-4.8 (Ubuntu 4.8.5-4ubuntu2) 4.8.5

I also have 4.8 installed.

**Comment by HowardLander** [comment]
Was there ever a resolution for this? I am seeing similar issues.
Thanks
Howard

**Comment by HowardLander** [comment]
Turns out the issue was that I am building my app with clang and the libs with g++. Oops...

**Comment by katmsft** [comment]
Hi,

Can you confirm that this issue still exsist on Ubuntu 16.04 for version later than 4.0.0?

**Comment by katmsft** [comment]
This issue is to be closed due to long time now response. Please feel free to contact us again or reopen the issue if this issue persist.

**Comment by bdjukic** [comment]
Hi there,

I'm seeing the same issue when trying to compile and link Azure Storage library with my ROS (Robotic Operating System) project.

This is my CMakeLists.txt file from the ROS project:

```
cmake_minimum_required(VERSION 2.8.3)
project(my_node)

add_compile_options(-std=c++11)

find_package(catkin REQUIRED COMPONENTS
  roscpp
  std_msgs
)

find_library(CPPREST_LIB cpprest)

find_package(OpenSSL 1.0.0 REQUIRED)
find_package(Boost REQUIRED COMPONENTS random system thread filesystem chrono atomic date_time regex)

include_directories(
  ${catkin_INCLUDE_DIRS}
  ${Boost_INCLUDE_DIRS}
)

set(CMAKE_CXX_FLAGS "-std=c++0x ${CMAKE_CXX_FLAGS}")

add_executable(${PROJECT_NAME} src/MyNode.cpp)

add_dependencies(${PROJECT_NAME} ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})

target_link_libraries(${PROJECT_NAME}
  ${catkin_LIBRARIES}
  ${Boost_LIBRARIES}
  ${CPPREST_LIB}
  OpenSSL::SSL
)
```

**Comment by bdjukic** [comment]
Ok, managed to solve this by importing Azure Storage CMake module from https://github.com/Azure-Samples/storage-blob-cpp-getting-started/tree/master/storage-blob-cpp-getting-started/cmake/Modules. 

And then used it in my CMakeLists.txt:

`find_package(AzureStorage REQUIRED)`

...

```
include_directories(
  ${AZURESTORAGE_INCLUDE_DIR}
  ${catkin_INCLUDE_DIRS}
  ${Boost_INCLUDE_DIRS}
)
```
...

```
target_link_libraries(${PROJECT_NAME}
  ${AZURESTORAGE_LIBRARIES}
  ${catkin_LIBRARIES}
  ${Boost_LIBRARIES}
  ${CPPREST_LIB}
  OpenSSL::SSL
)
```

**Comment by Pruxis** [comment]
I'm having a similar issue 

Hello.cpp:(.text+0x285): undefined reference to `azure::storage::cloud_storage_account::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

Using following CMakeLists.txt

```
cmake_minimum_required(VERSION 3.10.2)
project (Hello)
add_compile_options(-std=c++11)
# Azure stuff

find_path(AZURESTORAGE_INCLUDE_DIRS was/blob.h REQUIRED)
find_library(AZURESTORAGE_LIBRARIES azurestorage REQUIRED)
include_directories(${AZURESTORAGE_INCLUDE_DIRS})
find_library(CPPREST_LIB cpprest)
find_package(Boost REQUIRED COMPONENTS random system thread filesystem chrono atomic date_time regex)
find_package(OpenSSL 1.0.0 REQUIRED)
find_package(cpprestsdk CONFIG REQUIRED)


add_library(AzureStorage STATIC IMPORTED GLOBAL)
set_target_properties(AzureStorage PROPERTIES IMPORTED_LOCATION ${AZURESTORAGE_LIBRARIES})
set_target_properties(AzureStorage PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${AZURESTORAGE_INCLUDE_DIRS})
set_target_properties(AzureStorage PROPERTIES INTERFACE_LINK_LIBRARIES ${CPPREST_LIB})


# End Azure stuff
set(CMAKE_CXX_FLAGS "-std=c++0x ${CMAKE_CXX_FLAGS}")
add_executable(Hello Hello.cpp)
target_link_libraries(Hello PRIVATE cpprest)
```

**Comment by JinmingHu-MSFT** [comment]
@Pruxis Can you try to add `AzureStorage` into `target_link_libraries` list?

**Comment by Pruxis** [comment]
> @Pruxis Can you try to add `AzureStorage` into `target_link_libraries` list?

I will try this, do I append it after cpprest? (no prior c++ exp)

**Comment by Pruxis** [comment]
@JinmingHu-MSFT Thanks that resolved that issue :) Up to the next 🤦 
`undefined reference to `boost::log::v2s_mt_posix::attribute::impl::operator delete(void*, unsigned long)'`

**Comment by JinmingHu-MSFT** [comment]
> I will try this, do I append it after cpprest? (no prior c++ exp)

The order doesn't matter if it's dynamic library, it matters if it's static library.

**Comment by JinmingHu-MSFT** [comment]
> @JinmingHu-MSFT Thanks that resolved that issue :) Up to the next 🤦
> `undefined reference to `boost::log::v2s_mt_posix::attribute::impl::operator delete(void*, unsigned long)'`

```
find_package(Boost REQUIRED COMPONENTS random system thread filesystem chrono atomic date_time regex)
find_package(OpenSSL 1.0.0 REQUIRED)
find_package(cpprestsdk CONFIG REQUIRED)
```
you found these packages but you didn't link them to the target `Hello`. This is what caused the link error.

**Comment by Pruxis** [comment]
@JinmingHu-MSFT I'm now receiving the following errors:
```
/opt/ABBYY/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(basic_types.cpp.o): In function `utility::new_uuid()':
/opt/ABBYY/vcpkg/buildtrees/azure-storage-cpp/src/v7.5.0-1d01ff61d2.clean/Microsoft.WindowsAzure.Storage/src/basic_types.cpp:37: undefined reference to `uuid_generate_random'
/opt/ABBYY/vcpkg/buildtrees/azure-storage-cpp/src/v7.5.0-1d01ff61d2.clean/Microsoft.WindowsAzure.Storage/src/xml_wrapper.cpp:82: undefined reference to `xmlTextReaderValue'
```

I would assume I'm missing some uuid and XML import but I've been googling for hours without result..
Is there somewhere a sample CMakeLists.txt I'm really struggeling to setup sample code to retrieve a blob from storage :/

Current CMake:

```
cmake_minimum_required(VERSION 3.10.2)
project (Hello)
add_compile_options(-std=c++11)
# Azure stuff

find_path(AZURESTORAGE_INCLUDE_DIRS was/blob.h REQUIRED)
find_library(AZURESTORAGE_LIBRARIES azurestorage REQUIRED)
include_directories(${AZURESTORAGE_INCLUDE_DIRS})
find_library(CPPREST_LIB cpprest)
find_package(Boost REQUIRED COMPONENTS log log_setup random system thread filesystem chrono atomic date_time regex)
find_package(OpenSSL 1.0.0 REQUIRED)
find_package(cpprestsdk CONFIG REQUIRED)
INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIR})
set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME ON)
add_library(AzureStorage STATIC IMPORTED GLOBAL)
set_target_properties(AzureStorage PROPERTIES IMPORTED_LOCATION ${AZURESTORAGE_LIBRARIES})
set_target_properties(AzureStorage PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${AZURESTORAGE_INCLUDE_DIRS})
set_target_properties(AzureStorage PROPERTIES INTERFACE_LINK_LIBRARIES ${CPPREST_LIB})
# End Azure stuff
set(CMAKE_CXX_FLAGS "-std=c++0x ${CMAKE_CXX_FLAGS}")
add_executable(Hello Hello.cpp)
target_link_libraries(Hello PRIVATE cpprest AzureStorage)
TARGET_LINK_LIBRARIES(Hello LINK_PUBLIC ${Boost_LIBRARIES})
```

Many thanks for the help already!

**Comment by JinmingHu-MSFT** [comment]
@Pruxis You still need to install libuuid and libxml2, and link to them
