### ISSUE TITLE
Facing issue while building library on Mac Machine 10.8 and onwards.

### ISSUE THREAD

**Issue by girishshetye14** [Azure/azure-storage-cpp#120]
Hi All,

I am facing issue while building library on Mac Machine 10.8 and onwards.
Please provide your solution.
Thanks in advance.

Following errors are logged as below
====================================
[  1%] Building CXX object src/CMakeFiles/azurestorage.dir/xmlhelpers.cpp.o
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:436:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:79:9: error: no member named 'strcoll' in the global namespace
using ::strcoll;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:80:9: error: no member named 'strxfrm' in the global namespace
using ::strxfrm;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:82:9: error: no member named 'memchr' in the global namespace; did you mean 'wmemchr'?
using ::memchr;
      ~~^
/usr/include/wchar.h:150:10: note: 'wmemchr' declared here
wchar_t *wmemchr(const wchar_t *, wchar_t, size_t);
         ^
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:436:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:86:9: error: no member named 'strcspn' in the global namespace
using ::strcspn;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:88:9: error: no member named 'strpbrk' in the global namespace
using ::strpbrk;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:90:9: error: no member named 'strrchr' in the global namespace; did you mean 'strchr'?
using ::strrchr;
      ~~^
/System/Library/Frameworks/Kernel.framework/Headers/string.h:81:14: note: 'strchr' declared here
extern char     *strchr(const char *s, int c);
                 ^
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:436:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:92:9: error: no member named 'strspn' in the global namespace
using ::strspn;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:94:9: error: no member named 'strstr' in the global namespace; did you mean 'strnstr'?
using ::strstr;
      ~~^
/System/Library/Frameworks/Kernel.framework/Headers/string.h:80:14: note: 'strnstr' declared here
extern char     *strnstr(char *s, const char *find, size_t slen);
                 ^
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:436:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:99:98: error: no member named 'strpbrk' in the global namespace; did you mean simply 'strpbrk'?
inline _LIBCPP_INLINE_VISIBILITY       char* strpbrk(      char* __s1, const char* __s2) {return ::strpbrk(__s1, __s2);}
                                                                                                 ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:99:46: note: 'strpbrk' declared here
inline _LIBCPP_INLINE_VISIBILITY       char* strpbrk(      char* __s1, const char* __s2) {return ::strpbrk(__s1, __s2);}
                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:100:88: error: no member named 'strrchr' in the global namespace; did you mean simply 'strrchr'?
inline _LIBCPP_INLINE_VISIBILITY       char* strrchr(      char* __s, int __c) {return ::strrchr(__s, __c);}
                                                                                       ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:100:46: note: 'strrchr' declared here
inline _LIBCPP_INLINE_VISIBILITY       char* strrchr(      char* __s, int __c) {return ::strrchr(__s, __c);}
                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:101:99: error: no member named 'memchr' in the global namespace; did you mean simply 'memchr'?
inline _LIBCPP_INLINE_VISIBILITY       void* memchr(      void* __s, int __c, size_t __n) {return ::memchr(__s, __c, __n);}
                                                                                                  ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:101:46: note: 'memchr' declared here
inline _LIBCPP_INLINE_VISIBILITY       void* memchr(      void* __s, int __c, size_t __n) {return ::memchr(__s, __c, __n);}
                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:102:97: error: no member named 'strstr' in the global namespace; did you mean simply 'strstr'?
inline _LIBCPP_INLINE_VISIBILITY       char* strstr(      char* __s1, const char* __s2) {return ::strstr(__s1, __s2);}
                                                                                                ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:102:46: note: 'strstr' declared here
inline _LIBCPP_INLINE_VISIBILITY       char* strstr(      char* __s1, const char* __s2) {return ::strstr(__s1, __s2);}
                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:105:9: error: no member named 'strtok' in the global namespace
using ::strtok;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:107:9: error: no member named 'strerror' in the global namespace
using ::strerror;
      ~~^
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:438:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cwchar:192:49: error: declaration conflicts with target of using declaration already in scope
inline _LIBCPP_INLINE_VISIBILITY const wchar_t* wmemchr(const wchar_t* __s, wchar_t __c, size_t __n) {return ::wmemchr(__s, __c, __n);}
                                                ^
/usr/include/wchar.h:150:10: note: target of using declaration
wchar_t *wmemchr(const wchar_t *, wchar_t, size_t);
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:82:9: note: using declaration
using ::memchr;
        ^
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:656:35: error: no matching function for call to 'memchr'
        {return (const char_type*)memchr(__s, to_int_type(__a), __n);}
                                  ^~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:101:46: note: candidate function not viable: no known conversion from 'const char_type *' (aka 'const char *') to 'void *' for 1st argument; take the address of the argument with &
inline _LIBCPP_INLINE_VISIBILITY       void* memchr(      void* __s, int __c, size_t __n) {return ::memchr(__s, __c, __n);}
                                             ^
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/Secom9/CloudLogging/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:40:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:156:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:133:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/locale:864:44: error: use of undeclared identifier 'errno'
        typename remove_reference<decltype(errno)>::type __save_errno = errno;
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/locale:864:53: error: no type named 'type' in the global namespace
        typename remove_reference<decltype(errno)>::type __save_errno = errno;
                                                  ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/locale:864:73: error: use of undeclared identifier 'errno'
        typename remove_reference<decltype(errno)>::type __save_errno = errno;
                                                                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/CMakeFiles/azurestorage.dir/xmlhelpers.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/azurestorage.dir/all] Error 2
make: *** [all] Error 2

**Comment by girishshetye14** [comment]
[StorageLibBuildError.txt](https://github.com/Azure/azure-storage-cpp/files/864132/StorageLibBuildError.txt)

**Comment by JasonYang-MSFT** [comment]
Can you share your build command?

**Comment by girishshetye14** [comment]
**Following are the steps performed during building library**
step1: brew install libxml++ ossp-uuid openssl
step2: brew install cpprestsdk
step3: cloning repository
git clone https://github.com/Azure/azure-storage-cpp.git
step4: building library
          step4.1: cd azure-storage-cpp/Microsoft.WIndowsAzure.Storage
          step4.2: mkdir build.release
          step4.3: cd build.release
          step4.4: cmake .. -DCMAKE_BUILD_TYPE=Release
          step4.5: make (failed during executing make command showing above posted errors)

**Comment by girishshetye14** [comment]
Hi JasonYang,

We have provided steps used to build library.

Please provide your input.

Thanks And Regards,
Girish Shetye.

**Comment by JasonYang-MSFT** [comment]
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:436:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:79:9: error: no member named 'strcoll' in the global namespace
using ::strcoll;

From this last line, "strcoll" is missing but used by cstring. Seems like an issue in c++ library. 

There is one thing you can confirm is to write a simpler program but with using cstring to see it works or not.

**Comment by girishshetye14** [comment]
Hi JasonYang

Following is the example taken from google related to strcoll where builded through terminal command
g++ filename.cpp on MAC OS X 10.10.
Example below:
#include <iostream>
#include <cstring>
#include <clocale>
 
int main()
{
    std::setlocale(LC_COLLATE, "cs_CZ.iso88592");
 
    const char* s1 = "hrnec";
    const char* s2 = "chrt";
 
    std::cout << "In the Czech locale: ";
    if(std::strcoll(s1, s2) < 0)
         std::cout << s1 << " before " << s2 << '\n';
    else
         std::cout << s2 << " before " << s1 << '\n';
 
    std::cout << "In lexicographical comparison: ";
    if(std::strcmp(s1, s2) < 0)
         std::cout << s1 << " before " << s2 << '\n';
    else
         std::cout << s2 << " before " << s1 << '\n';
}
link from example taken:
http://en.cppreference.com/w/cpp/string/byte/strcoll

compile like:
g++ filename.cpp
./a.out

Please provide your view on this.

Thanks And Regards,
Girish Shetye

**Comment by girishshetye14** [comment]
Hi JasonYang,

Any input from your side please?

Thanks And Regards,
Girish Shetye

**Comment by girishshetye14** [comment]
Hi JasonYang,

Any input from your side please?

Thanks And Regards,
Girish Shetye

**Comment by JasonYang-MSFT** [comment]
I also don't have clue on this issue. And I don't have Mac to try this. #72 is the PR to fix build issue on OSX. I compared the command, it seems that the differ is at build command:
CASABLANCA_DIR=<path to Casablanca> cmake .. -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=<path to openssl> -DGETTEXT_LIB_DIR=<path to gettext lib dir>

**Comment by stevenimle** [comment]
+1 on this issue.

```
[  1%] Building CXX object src/CMakeFiles/azurestorage.dir/xmlhelpers.cpp.o
In file included from /Users/h246536/CLionProjects/azure-storage-cpp/Microsoft.WIndowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/h246536/CLionProjects/azure-storage-cpp/Microsoft.WIndowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:171:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:638:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:79:9: error: no member named 'strcoll' in the global namespace
using ::strcoll;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:80:9: error: no member named 'strxfrm' in the global namespace
using ::strxfrm;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:81:9: error: no member named 'memchr' in the global namespace; did you mean 'wmemchr'?
using ::memchr;
      ~~^
/usr/include/wchar.h:150:10: note: 'wmemchr' declared here
wchar_t *wmemchr(const wchar_t *, wchar_t, size_t);
         ^
In file included from /Users/h246536/CLionProjects/azure-storage-cpp/Microsoft.WIndowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/h246536/CLionProjects/azure-storage-cpp/Microsoft.WIndowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:171:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:638:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:83:9: error: no member named 'strcspn' in the global namespace
using ::strcspn;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:84:9: error: no member named 'strpbrk' in the global namespace
using ::strpbrk;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:85:9: error: no member named 'strrchr' in the global namespace; did you mean 'strchr'?
using ::strrchr;
      ~~^
/System/Library/Frameworks/Kernel.framework/Headers/string.h:81:14: note: 'strchr' declared here
extern char     *strchr(const char *s, int c);
                 ^
In file included from /Users/h246536/CLionProjects/azure-storage-cpp/Microsoft.WIndowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/h246536/CLionProjects/azure-storage-cpp/Microsoft.WIndowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:171:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:638:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:86:9: error: no member named 'strspn' in the global namespace
using ::strspn;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:87:9: error: no member named 'strstr' in the global namespace; did you mean 'strnstr'?
using ::strstr;
      ~~^
/System/Library/Frameworks/Kernel.framework/Headers/string.h:80:14: note: 'strnstr' declared here
extern char     *strnstr(char *s, const char *find, size_t slen);
                 ^
In file included from /Users/h246536/CLionProjects/azure-storage-cpp/Microsoft.WIndowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/h246536/CLionProjects/azure-storage-cpp/Microsoft.WIndowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:171:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:638:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:89:9: error: no member named 'strtok' in the global namespace
using ::strtok;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:92:9: error: no member named 'strerror' in the global namespace
using ::strerror;
      ~~^
In file included from /Users/h246536/CLionProjects/azure-storage-cpp/Microsoft.WIndowsAzure.Storage/src/xmlhelpers.cpp:42:
In file included from /Users/h246536/CLionProjects/azure-storage-cpp/Microsoft.WIndowsAzure.Storage/includes/stdafx.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:40:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/istream:163:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ostream:140:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:695:44: error: use of undeclared identifier 'errno'
        typename remove_reference<decltype(errno)>::type __save_errno = errno;
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:695:53: error: no type named 'type' in the global namespace
        typename remove_reference<decltype(errno)>::type __save_errno = errno;
                                                  ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:695:73: error: use of undeclared identifier 'errno'
        typename remove_reference<decltype(errno)>::type __save_errno = errno;
                                                                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:696:9: error: use of undeclared identifier 'errno'
        errno = 0;
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:699:44: error: use of undeclared identifier 'errno'
        typename remove_reference<decltype(errno)>::type __current_errno = errno;
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:699:53: error: no type named 'type' in the global namespace
        typename remove_reference<decltype(errno)>::type __current_errno = errno;
                                                  ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:699:76: error: use of undeclared identifier 'errno'
        typename remove_reference<decltype(errno)>::type __current_errno = errno;
                                                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:701:13: error: use of undeclared identifier 'errno'
            errno = __save_errno;
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/locale:735:44: error: use of undeclared identifier 'errno'
        typename remove_reference<decltype(errno)>::type __save_errno = errno;
                                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/CMakeFiles/azurestorage.dir/xmlhelpers.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/azurestorage.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by epowers** [comment]
Add `-DCMAKE_FIND_FRAMEWORK=LAST` to the cmake command.

Successfully built using MacPorts for dependencies and this cmake command:

`cmake .. -DCMAKE_BUILD_TYPE=Release -DGETTEXT_LIB_DIR=/opt/local/lib -DCMAKE_FIND_FRAMEWORK=LAST`

Output:

`[ 98%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_common.cpp.o`
`[100%] Linking CXX shared library ../Binaries/libazurestorage.dylib`
`[100%] Built target azurestorage`

Google searches reveal other projects with the same issue... though I have not explored the core problem.

**Comment by stevenimle** [comment]
That was one of the things I tried, there was still an issue getting it to function. I am using brew for my dependencies. The issue also happens whether I build the cpprestsdk from source or install it manually. (Just thought I'd mention that since it is something that I have tried.)

**Comment by girishshetye14** [comment]
Hi Steve,
I will try your suggestion. To install dependencies i use brew command but still it fails.Also tried manual building command getting the same result.
I will do your suggested command.

**Comment by vinjiang** [comment]
Feel free to let us know if  we can be of any further assistance.

**Comment by katmsft** [comment]
@rizkg This suggestion is duly noted and will be added to the instructions. Thanks!
