### ISSUE TITLE
Copy status is always sucess

### ISSUE THREAD

**Issue by kvp** [Azure/azure-storage-cpp#127]
I'm using the blob.start_copy function to copy a file inside azure and right after it trying to access it,
I'm testing if the blob.copy_state().status() is success before accessing it and it's always returning success, but sometimes when I try to access the file, it's not there, my guess is that the file copy isn't copied yet and blob.copy_state().status() isn't updated.
So, how can I assure the copy is already finished?

**Comment by JasonYang-MSFT** [comment]
@kvp Can you provide some detail network trace or client id used to request copy for deeper learning on this issue?

After start copy, you can call exist on target blob to see whether it is already exists or not.

**Comment by kvp** [comment]
Ok, thanks!
I will try to call target_blob.exists()

But I'm still not sure when copy_state().status() is updated, it's updated when we call it, or do we have to call blob.download_attributes to make sure it's the last valid value?

**Comment by katmsft** [comment]
The value of `copy_state().status()` only updates when you call operations that might potentially updates the blob's attribute, say `get_blob` or `download_attributes`.

**Comment by vinjiang** [comment]
Please reopen this issue if you need further assistance.
