### ISSUE TITLE
is there a way to get the azure storage sdk version programatically

### ISSUE THREAD

**Issue by Eliyahu-Machluf** [Azure/azure-storage-cpp#129]
Hi,

I'm writing a utility which uses the azure-storge-cpp SDK, and I want to log the SDK version. Is there a way I can know (on run-time or compile time) the SDK version?

Thanks.

**Comment by achie-liang** [comment]
Hi,

Sorry for late response.
One way to get SDK version is to access azure::storage::protocol::header_value_user_agent, which containing User-Agent header value of the SDK. 
You may check the value in wascore/constants.dat, the value should be something like "Azure-Storage/x.x.x  ...", x.x.x here is the SDK version. Or you can just use this value directly for logging.

**Comment by Eliyahu-Machluf** [comment]
OK. 
Thanks.
