### ISSUE TITLE
exception after get_shared_access_signature

### ISSUE THREAD

**Issue by hs79hs** [Azure/azure-storage-cpp#130]
I have a simple function which gets SAS using a policy set before. It likes,

wstring NVR::GetAccessPolicy(string eventID)
{
	auto container = blob_client.get_container_reference(L"1234");
	utility::string_t policy_name = L"Signature";
	auto token = container.get_shared_access_signature(azure::storage::blob_shared_access_policy(), policy_name);

	return token;
}

The token it returned is right. I can use it to access my blobs. But there is always an exception thrown while exiting this function. It said a breakpoint was triggered and stopped at the last line of _Deallocate() in "C:\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xmemory0",

::operator delete(_Ptr);

If not calling get_shared_access_signature, everything is okay.
Could someone tell me why this happened? I cannot find any examples of how to get SAS of a container. Thanks.

**Comment by hs79hs** [comment]
Just found this only happened when building in Debug. If in Release, everything is ok. So maybe it's related to compiling environment

**Comment by JasonYang-MSFT** [comment]
Hi @hs79hs ,

I tried your sample in vs 2017 enterprise, it works fine. And you are already getting SAS in a right way.

Can you give a stack trace when this issue happened?  Also, is it possible this issue caused by logic after it returned a correct sas token?

**Comment by vinjiang** [comment]
Feel free to let us know if you need further assistance.
