### ISSUE TITLE
Build issue caused by macro "min"

### ISSUE THREAD

**Issue by TiTi** [Azure/azure-storage-cpp#132]
I have a build issue on a project using Windows SDK 10.0.14393.0

was/common.h is using **std::min** in `size_t get_remaining_results_num() const`
```
return (size_t)std::min(m_max_results - m_returned_results, (utility::size64_t)m_max_results_per_segment);
```

The compilation error:
> Error	C2589	'(': illegal token on right side of '::' 

This is because this file in included in my project:
Windows Kits\10\Include\10.0.14393.0\shared\minwindef.h:
```
#ifndef min
#define min(a,b)            (((a) < (b)) ? (a) : (b))
#endif
 ```

Thus, `std::min` is affected by the macro...

It seems to have been fixed for max, but not min, cf #113 and d873b415b34935956fd5465645b68b8dbe9b862c

---

This happens when using the `azure::storage::list_blob_item_iterator` from a snippet provided on this page : https://docs.microsoft.com/en-us/azure/storage/common/storage-c-plus-plus-enumeration

**Comment by JasonYang-MSFT** [comment]
Hi @TiTi,
I have verified this issue, gonna to fix it in dev branch. Thanks a lot for file this issue.
