### ISSUE TITLE
Azure-storage-cpp fails to compile with latest cpprestsdk

### ISSUE THREAD

**Issue by PascalJedi** [Azure/azure-storage-cpp#134]
Build latest RESTCPP 
(https://github.com/Microsoft/cpprestsdk)

My guess is commit c1a4067d82f07a218a9f71fb68badac05afff9e8 is what caused everything to stop working. 

azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h:370:20: error: ‘do_while’ is not a member of ‘pplx::details’
             return pplx::details::do_while([instance]() -> pplx::task<bool>

// Build Script
sudo apt-get install -y  g++ git make zlib1g-dev libboost-all-dev libssl-dev cmake
sudo apt-get install -y uuid-dev
sudo apt-get install -y libxml++2.6-dev libxml++2.6-doc uuid-dev
sudo apt-get install -y libunittest++-dev

git clone https://github.com/Microsoft/cpprestsdk.git casablanca

cd casablanca/Release
mkdir build.debug
cd build.debug
cmake .. -DCMAKE_BUILD_TYPE=Release 
make

sudo make install

cd ..
cd ..
cd ..

git clone https://github.com/Azure/azure-storage-cpp.git

cd azure-storage-cpp/Microsoft.WindowsAzure.Storage
mkdir build.release
cd build.release
CASABLANCA_DIR=../../../Casablanca/cpprestsdk/ CXX=g++-4.8 cmake .. -DCMAKE_CXX_
COMPILER=/usr/bin/g++   -DCMAKE_BUILD_TYPE=Release  
make
sudo make install

**Comment by PascalJedi** [comment]
If the error message wasn't clear here it is again

[  1%] Building CXX object src/CMakeFiles/azurestorage.dir/response_parsers.cpp.o
In file included from /XXXX/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/protocol.h:25:0,
                 from /XXXX/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:19:
/XXXX/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h: In static member function ‘static pplx::task<void> azure::storage::core::executor_impl::execute_async(std::shared_ptr<azure::storage::core::storage_command_base>, const azure::storage::request_options&, azure::storage::operation_context)’:
/XXXX/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h:370:20: error: ‘do_while’ is not a member of ‘pplx::details’
             return pplx::details::do_while([instance]() -> pplx::task<bool>

**Comment by JasonYang-MSFT** [comment]
Hi @PascalJedi ,

We haven't integrate with newest cpprestsdk(2.10.0) yet. Currently you can work it with 2.9.1.1.
Is there any significant feature in 2.10.0 you want to use?

**Comment by xinglin** [comment]
Just FYI, I am hitting the same issue...

-Xing

**Comment by katmsft** [comment]
This issue has already been resolved in 5.1.0, please check out the README.txt for more details of the tested Casablanca version of this SDK.
