### ISSUE TITLE
Thread safety. Is the cloud_storage_account and cloud_blob_client thread safe?

### ISSUE THREAD

**Issue by sbailey476** [Azure/azure-storage-cpp#138]
I can't find any documentation about thread safety. 

Is the cloud_storage_account and cloud_blob_client thread safe? Or should I create one for each thread?

**Comment by JasonYang-MSFT** [comment]
Most of their methods are thread safe, but for to_string in cloud_storage_account and set_authentication_scheme in cloud_blob_client, they are overwriting members which is not thread safe.

**Comment by vinjiang** [comment]
Feel free to contact us if you need further assistance.
