### ISSUE TITLE
Parallel download wont work for range downloads with a offset greater than zero

### ISSUE THREAD

**Issue by sbailey476** [Azure/azure-storage-cpp#144]
I'm using version 3.1.0 and parallel download wont work for downloads where the offset is greater than zero. The issue is the SDK is trying to write passed the end of the target output stream.

On line 658 of cloud_blob.cpp the SDK is trying to seek the target output stream to the current offset of the data in the cloud.

`target.streambuf().seekpos(current_offset, std::ios_base::out);`

**Comment by JasonYang-MSFT** [comment]
Hi @sbailey476 ,

I have opened a bug for this issue. Will fix it soon.

Thanks,
-Jason
