### ISSUE TITLE
Download range to stream doesn't return how much data was actually downloaded and written

### ISSUE THREAD

**Issue by sbailey476** [Azure/azure-storage-cpp#145]
With the following code I am downloading a range of data from a cloud blob to a memory buffer. However I cannot see anyway to get how much data was actually downloaded and written to the output stream. The offset + length might be passed the end of the blob in which case I would just expect only the data until the end of the blob to be downloaded.

`
basic_ostream<uint8_t> out_stream = rawptr_stream<uint8_t>::open_ostream(pData, length);
pplx::task<void> dowload_task = my_object.download_range_to_stream_async(out_stream, offset, length);`

**Comment by JasonYang-MSFT** [comment]
If parallel is not enabled, this api will call to download a range data [offset, offset+length). if offset + length is larger than blob's actual length, only the data until the end of the blob will be downloaded.

Currently in parallel download, it will split the range [offset, offset + length). If any of splatted range's offset is larger than blob's actual size, it fails now. Will fix it to ignore these cases and make the download success latter.
