### ISSUE TITLE
build sample code error

### ISSUE THREAD

**Issue by DandelionWenjing** [Azure/azure-storage-cpp#153]
I have met some problems when I build the sample code:

**os:** ubuntu 
build sdk successfully and get the .so file.

**error details:**
~/azure-storage-cpp/Microsoft.WindowsAzure.Storage/build.release$ make
[ 81%] Built target azurestorage
[ 84%] Built target samplescommon
[ 86%] Linking CXX executable ../../Binaries/samplesblobs
CMakeFiles/samplesblobs.dir/Application.cpp.o: In function `azure::storage::samples::blobs_getting_started_sample()':
Application.cpp:(.text+0x1365): undefined reference to `utility::conversions::to_utf8string(std::string)'
Application.cpp:(.text+0x13db): undefined reference to `utility::conversions::to_utf8string(std::string)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::uri::encode_data_string(std::string const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::uri::decode(std::string const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::etag'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::uri::uri(std::string const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::if_match'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::uri::encode_impl(std::string const&, std::function<bool (int)> const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::content_range'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::if_modified_since'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::methods::MERGE'
../../Binaries/libazurestorage.so.3.1: undefined reference to `utility::conversions::from_base64(std::string const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::uri::split_path(std::string const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::json::value::value(std::string)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::uri::split_query(std::string const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::methods::GET'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::user_agent'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::json::value::parse(std::string const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::methods::HEAD'
../../Binaries/libazurestorage.so.3.1: undefined reference to `utility::datetime::from_string(std::string const&, utility::datetime::date_format)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::methods::DEL'
../../Binaries/libazurestorage.so.3.1: undefined reference to `utility::conversions::to_base64(std::vector<unsigned char, std::allocator<unsigned char> > const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::methods::PUT'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::if_none_match'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::last_modified'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::uri_builder::append_query(std::string const&, bool)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::if_unmodified_since'
../../Binaries/libazurestorage.so.3.1: undefined reference to `utility::conversions::to_string_t(std::string const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `utility::conversions::to_string_t(std::string&&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::range'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::uri_builder::append_path(std::string const&, bool)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::details::_http_request::_http_request(std::string)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::json::value::serialize() const'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::json::value::object(std::vector<std::pair<std::string, web::json::value>, std::allocator<std::pair<std::string, web::json::value> > >, bool)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `utility::datetime::to_string(utility::datetime::date_format) const'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::content_type'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::content_length'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::details::http_msg_base::set_body(Concurrency::streams::basic_istream<unsigned char> const&, unsigned long, std::string const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::cache_control'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::content_language'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::json::value::as_string() const'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::date'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::accept_charset'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::accept'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::methods::POST'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::authorization'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::content_encoding'
../../Binaries/libazurestorage.so.3.1: undefined reference to `Glib::ustring::ustring(std::string const&)'
../../Binaries/libazurestorage.so.3.1: undefined reference to `web::http::header_names::content_md5'
collect2: error: ld returned 1 exit status
samples/BlobsGettingStarted/CMakeFiles/samplesblobs.dir/build.make:115: recipe for target 'Binaries/samplesblobs' failed
make[2]: *** [Binaries/samplesblobs] Error 1
CMakeFiles/Makefile2:229: recipe for target 'samples/BlobsGettingStarted/CMakeFiles/samplesblobs.dir/all' failed
make[1]: *** [samples/BlobsGettingStarted/CMakeFiles/samplesblobs.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by katmsft** [comment]
This issue is acked, will be further investigated on. Please stay tuned.

**Comment by katmsft** [comment]
Hi, I cannot seem to reproduce your issue. Please make sure that the Casablanca version is 2.9.1 and the command for compiling the sample is:
```
CASABLANCA_DIR=<path to Casablanca> CXX=g++-4.8 cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SAMPLES=ON
make
```

**Comment by Dyutighosh** [comment]
@katmsft Hi sir, I am also facing the same issue , I have followed the exact same procedure that is given in the documentation and also used Casablanca version 2.9.1. 
SDK is building fine but samples are not compiling for me. can you please look into this issue.

@DandelionWenjing have you find any solution to your problem ,sir?

**Comment by katmsft** [comment]
@Dyutighosh Thanks for reporting the issue. If you are facing the same issue it means there is something wrong when linking the 'casablanca' library since all the symbols are not found during linking steps. This indicates either there is a problem of locating the 'casablanca' library, which will be detected when running cmake, or the found library cannot be paired with the .h files found during compiling. 
It is possible that there are several 'casablanca' library installed in the building environment, so please make sure you deleted any of them that is not 2.9.1 to make sure the correct library is loaded during compile.

**Comment by Dyutighosh** [comment]
@katmsft  Thank you sir for your reply. I am using the new azure blob storage SDK along with casablanca 2.9.1 given in the following link. Also I do not have any other restcpp library in my system. 
Still i am getting the above error. 
https://github.com/Microsoft/cpprestsdk/tree/v2.9.1

**Comment by hmz20000** [comment]
@Dyutighosh I was having the same issue. I think it is system-specific issue so I get a VM with Ubuntu 14.04 and repeat all steps, and it works. Hope it helps.

**Comment by katmsft** [comment]
Hi,
It seems that the issue occurs during the Linking, and I suffer from this issue when there are multiple installations of CPPRestsdk in the system. Can you check with a clean Linux environment?
My own validation for samples/tests are executed from a Dockerfile using Docker so it can ensure that the running environment is clean.

**Comment by katmsft** [comment]
This issue is to be closed due to long time now response. Please feel free to contact us again or reopen the issue if this issue persist.
