### ISSUE TITLE
Compilation error on SuSE 12SP2

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-storage-cpp#155]
Hi All,

New developer here for Azure Storage SDK. And I am using SLES12SP2 as my platform.
What's the minimal C++ compiler requirement for this project please? C++ 11 or 14?
I've run into the following errors and couldn't find a solution:
In file included from /var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/streambuf.h:23:0,
                 from /var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/streams.h:21,
                 from /var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h:25,
                 from /var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/protocol.h:25,
                 from /var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:19:
/var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/hashing.h:176:18: error: field ‘m_hash_context’ has incomplete type
         HMAC_CTX m_hash_context;
                  ^
In file included from /var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/protocol.h:25:0,
                 from /var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:19:
/var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h: In static member function ‘static pplx::task<void> azure::storage::core::executor_impl::execute_async(std::shared_ptr<azure::storage::core::storage_command_base>, const azure::storage::request_options&, azure::storage::operation_context)’:
/var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h:369:20: error: ‘do_while’ is not a member of ‘pplx::details’
             return pplx::details::do_while([instance]() -> pplx::task<bool>
                    ^
/var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h: In lambda function:
/var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h:473:148: warning: ‘utility::string_t utility::conversions::print_string(const Source&, const std::locale&) [with Source = short unsigned int; utility::string_t = std::basic_string<char>]’ is deprecated (declared at /usr/local/include/cpprest/asyncrt_utils.h:208): All locale-sensitive APIs will be removed in a future update. Use stringstreams directly if locale support is required. [-Wdeprecated-declarations]
                         str.append(_XPLATSTR("Response received. Status code = ")).append(utility::conversions::print_string(response.status_code())).append(_XPLATSTR(". Reason = ")).append(response.reason_phrase());
                                                                                                                                                    ^
/var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h: In lambda function:
/var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h:663:166: warning: ‘utility::string_t utility::conversions::print_string(const Source&, const std::locale&) [with Source = int; utility::string_t = std::basic_string<char>]’ is deprecated (declared at /usr/local/include/cpprest/asyncrt_utils.h:208): All locale-sensitive APIs will be removed in a future update. Use stringstreams directly if locale support is required. [-Wdeprecated-declarations]
                             str.append(_XPLATSTR("Retrying failed operation, number of retries: ")).append(utility::conversions::print_string(instance->m_retry_count));
                                                                                                                                                                      ^
/var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp: In function ‘std::chrono::seconds azure::storage::protocol::parse_lease_time(const web::http::http_response&)’:
/var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:160:79: warning: ‘Target utility::conversions::scan_string(const string_t&, const std::locale&) [with Target = long int; utility::string_t = std::basic_string<char>]’ is deprecated (declared at /usr/local/include/cpprest/asyncrt_utils.h:304): All locale-sensitive APIs will be removed in a future update. Use stringstreams directly if locale support is required. [-Wdeprecated-declarations]
             int64_t seconds = utility::conversions::scan_string<int64_t>(value);
                                                                               ^
/var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp: In function ‘int azure::storage::protocol::parse_approximate_messages_count(const web::http::http_response&)’:
/var/opt/teradata/yang/azure-storage-cpp/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:174:64: warning: ‘Target utility::conversions::scan_string(const string_t&, const std::locale&) [with Target = int; utility::string_t = std::basic_string<char>]’ is deprecated (declared at /usr/local/include/cpprest/asyncrt_utils.h:304): All locale-sensitive APIs will be removed in a future update. Use stringstreams directly if locale support is required. [-Wdeprecated-declarations]
             return utility::conversions::scan_string<int>(value);
                                                                ^
src/CMakeFiles/azurestorage.dir/build.make:86: recipe for target 'src/CMakeFiles/azurestorage.dir/response_parsers.cpp.o' failed
make[2]: *** [src/CMakeFiles/azurestorage.dir/response_parsers.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/azurestorage.dir/all' failed
make[1]: *** [src/CMakeFiles/azurestorage.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Can somebody please help me out in figuring out the errors?

Thanks,

Yang

**Comment by katmsft** [comment]
This issue is acknowledged, I'll take some time investigate this issue, please stay tuned.

**Comment by katmsft** [comment]
Hi, the compiler requirement is c++11.

There are two reported errors by the compiler, the first one is `field ‘m_hash_context’ has incomplete type HMAC_CTX m_hash_context`, you can reference [this](https://github.com/butor/blackbird/issues/353) for solution. I myself has not encountered this problem during build, once all the dependencies are set correct.

The second reported error is `‘do_while’ is not a member of ‘pplx::details’`. And I believe this is caused by using the wrong version of casablanca. This SDK depends on 2.9.1 so please make sure that build this version of casablanca instead of any other version.

I can successfully build the SDK with the correct setting. But please feel free to report any other problems during compile.

**Comment by vinjiang** [comment]
Please let us know if you still need assistance from us.
