### ISSUE TITLE
Build with bazel to support TensorFlow filesystem plugin

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-storage-cpp#166]
TensorFlow can use [Filesystem Plugins](https://www.tensorflow.org/extend/add_filesys) for ease of utilisation of different storage systems. Currently this has GCS, S3, Hadoop etc and I'd love to be able to use azure blob/file storage here. Prefix and path to be something like 'azbs://account/container/file.txt' or 'azfs://account/container/file.txt'

The TensorFlow project uses bazel to build and I've seen has custom build rules setup in their repositories to support some of these storage systems pulling from third party git repos (e.g. the s3 adapter).

I've had a brief go of trying to get the azure-storage-cpp project built with bazel but keep running into difficulties. Just seeing if this is something the azure storage team would be keen to support and/or look into?

**Comment by JasonYang-MSFT** [comment]
Hi @damienpontifex , you can drop me an email on the detail issues to see whether I can help.

**Comment by damienpontifex** [comment]
Thanks @JasonYang-MSFT I've decided to implement the REST calls myself using libcurl and boringssl. TensorFlow already has these as dependencies and the interface for manipulation is only a few operations so don't need everything reimplemented.

Thanks for reaching out though
