### ISSUE TITLE
Questions regarding client side logging and error handling

### ISSUE THREAD

**Issue by cosmosb** [Azure/azure-storage-cpp#168]
Hi All,

I have few questions:

(1) Is there any way to have client side logging at all? If yes, how do you do that?

I can't find any reliable information about this. It seems Java and .Net flavor of SDKs have client side logging but not others including this. I would like to output logs to a file.

(2) In case of error it throws exception. Will exception object always contain extended information? Reason I'm asking is because I'm trying to download non-existing blob, and all I get is string error message: **The specified blob does not exist.**. Request result object doesn't contain any information either.

I was expecting error code: BlobNotFound. Ref: https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes
	
Checking string value is not best way as it can change in future. How do I get better error code and error description?

**Comment by katmsft** [comment]
Hi, thanks for raising the issue.

(1) There is currently no support for client side logging. We have this item in our backlog but we are not prioritizing it because lacking of evidence that this is an urgent request from our customers.

(2) Currently, performing some operation on a blob that might not exist is not a recommended approach for our customers. Although we do not pack the error code in our exception, we do provide function `azure::storage::cloud_blob::exists` that will provide such information. It is advised that our user always uses this before perform any operation on a blob that might not exists, except for two scenarios.

The first scenario is when the performance of getting a blob is critical for a user and the blobs to be get is large in quantity but small in size in general. Calling `exists` could have impact on performance since it makes REST call to the server.

The second scenario is when user have a very good idea of what an exception message would be when a non-existing blob is operated on. This way it is lighter and more flexible for one to make oneself's own exception handling logic for non-existing blob. But as you mentioned, the string value can change in the future so the potential risk should be understood by our user clearly.

Hope this answers your questions, please feel free to raise further questions.

**Comment by cosmosb** [comment]
Yes, there will be high number of blobs with small size in the app. For now, instead of checking exception string, I'm checking http status code, which would not change frequently.

```
catch (const azure::storage::storage_exception &e) {
	if (e.result().http_status_code() == web::http::status_codes::NotFound) {
               // Handle missing blob
        }
}
```

> (1) Edit: There is a logging system in the SDK, in Windows, event log is used and in linux, the log will be output to a file if log level is set. I'll post a more detailed reply of how to use it.

Looking forward to this information.

**Comment by katmsft** [comment]
Hi @cosmosb , I have pasted here the guide from @JasonYang-MSFT for logging in CPP SDK.

From @JasonYang-MSFT :

I have summarized following content for traces. Please check it out. 

**Turn on Traces:**
There are two ways to turn on trace in Azure Storage C++ client library. One is to set a global log level to enable logger, another one is per operation logging.

**Set global log level:**
    `azure::storage::operation_context::set_default_log_level(azure::storage::client_log_level::log_level_verbose);`
        All the traces with lower or equal log level to log_level_verbose will be traces. Actually, all traces are turned on because log_level_verbose is the highest level.

**Per operation:**
```
    auto account = azure::storage::cloud_storage_account::parse(connection_string);
    auto client = account.create_cloud_blob_client();
    auto container = client.get_container_reference(_XPLATSTR("container"));
    container.create_if_not_exists();

    auto blob = container.get_block_blob_reference(_XPLATSTR("blob"));
    azure::storage::operation_context op;
    op.set_log_level(azure::storage::client_log_level::log_level_verbose);
    blob.upload_text(_XPLATSTR("test"),azure::storage::access_condition(), azure::storage::blob_request_options(), op);
```
Only traces in this API call this time will be turned on.

Besides, there are 5 log levels[1]: `log_level_off`, `log_level_error`, `log_level_warning`, `log_level_informational` and `log_level_verbose`. Traces with lower or equal log level to the log level you set will be turned on.
For example, if you set log level to `log_level_warning`, only traces with level `log_level_error` and `log_level_warning` will be traced. Specially, `log_level_verbose` will trace all logs and `log_level_off` will turn off all traces. In default, log level is set to `log_level_off`.

**Collect the Traces:**
There are also different ways to collect the traces on Windows and Linux. 
For Linux platform, trace log will be directly written in a file. The file path could be specified. See in following sample[2] code:
```
    boost::log::add_file_log
    (
        boost::log::keywords::file_name = "test_log.log",
        boost::log::keywords::format = 
        (
            boost::log::expressions::stream << "<Sev: " << boost::log::trivial::severity
            << "> " << boost::log::expressions::smessage
        )
);
```
For Windows platform, you need to use tracing tools[3] to collect traces. 
Take tool logman on windows for example:
First, create a trace session with logman by : 
logman create trace mysession 
    Then start the tracing with specified GUID[4]:
logman start mysession 
`-p {EE5D17C5-1B3E-4792-B0F9-F8C5FC6AC22A} `
`-o mytest.etl -ets`
Finally stop the trace session and export the traces:
`logman stop mysession -ets`
`tracerpt mytest.etl`
There will be two files: summary and dumpfile.

[1]Log level reference: https://github.com/Azure/azure-storage-cpp/blob/24219e816b088fbb64a359d92ff590245ccf0b90/Microsoft.WindowsAzure.Storage/includes/was/common.h#L1452
[3]Trace output sample on Linux platform: https://github.com/Azure/azure-storage-cpp/blob/24219e816b088fbb64a359d92ff590245ccf0b90/Microsoft.WindowsAzure.Storage/tests/main.cpp#L49
[2]Tracing tool reference: https://msdn.microsoft.com/en-us/library/windows/desktop/aa363883(v=vs.85).aspx 
[4[]Azure Storage C++ logger guid: https://github.com/Azure/azure-storage-cpp/blob/24219e816b088fbb64a359d92ff590245ccf0b90/Microsoft.WindowsAzure.Storage/src/logging.cpp#L42

**Comment by cosmosb** [comment]
@katmsft Thank you for all information.

**Comment by crusader-mike** [comment]
Hi. Is there any way to intercept logging in my client app? As in "intercept and write to my own log file"... It seems that I can do it on Linux via `azure::storage::operation_context::set_logger()`, but I can't find anything like that on Windows.

**Comment by JasonYang-MSFT** [comment]
Yes, here is an example on using krabsetw to capture etw traces with c++ on windows: https://github.com/Microsoft/krabsetw/blob/master/examples/NativeExamples/user_trace_001.cpp#L20

You may need to replace the etw provider id with "EE5D17C5-1B3E-4792-B0F9-F8C5FC6AC22A".

**Comment by crusader-mike** [comment]
Thank you! Yes, looks like it is going to work. I am just concerned that I'll end up consuming all such events in every instance of my app (and discarding those with wrong process id) -- this isn't ideal (if true). Unfortunately I add azure support to existing application and can't change it's logging model.

Another concern is that apparently ETW doesn't guarantee that observe will see all event (i.e. if machine is under heavy load) -- this is even worse (if true).

**Comment by howryu** [comment]
Is there any reason why `azure::storage::operation_context::set_logger()` is not supported on windows? I can see from source code that this method is not defined on windows.

**Comment by katmsft** [comment]
Since all questions are resolved, this issue will now be closed.

**Comment by crusader-mike** [comment]
@katmsft, @vinjiang questions are answered, but solution wasn't found -- there is no way to reliably intercept all logging (I do not consider messing with function entry points a good solution). Would be nice if azure sdk got updated with such feature...

**Comment by katmsft** [comment]
Since this conversation has diverged into multiple topics, can you kindly open another issue stating the problem you want to fix/resolve or feature you want to add to better tracking it? @crusader-mike , thanks!

**Comment by crusader-mike** [comment]
@katmsft Done. See #296
