### ISSUE TITLE
Creating cloud_block_blob object using SAS token

### ISSUE THREAD

**Issue by bkmcfarland** [Azure/azure-storage-cpp#169]
I'm overlooking something when I attempt to create a cloud_block_blob object using a SAS token with the URI constructor and the URI,storage_credentials constructor. Can you explain what I'm overlooking?

  utility::string_t sasToken = create_container_shared_policy(container);
  ucout << U("<<< SAS Service Token >>>  ") << sasToken << std::endl;

  storage_credentials sasCreds = storage_credentials(sasToken);

  web::http::uri primaryaccountURI = accountURI.primary_uri();
  //web::http::uri secondaryaccountURI = accountURI.secondary_uri();

  web::http::uri sasprimaryURI = sasCreds.transform_uri(primaryaccountURI);
  //Instantiate a SAS based instance of the storage_uri
  storage_uri sas_URI = storage_uri(sasprimaryURI);
 
 cloud_block_blob block_blob = cloud_block_blob(sas_URI, sasCreds);

The attempt to create the cloud_block_blob() using the URI/SAS token storage_uri,storage_credentials constructor throws the following exception:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Cannot provide credentials as part of the address and as constructor parameter. Either pass in the address or use a different constructor.

Attempting to create the cloud_block_blob() using the URI constructor using a URI/SAS token throws the following exception:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  uri

The above code generates the following SAS token:
<<< SAS Service Token >>>  sv=2016-05-31&si=containerSASPolicy&sig=sLJTvzvl9%2FSLP6zj1%2FQQBwp7JtGD7T3tCxmlcWizwJI%3D&spr=https%2Chttp&se=2018-04-20T15%3A56%3A04Z&sp=racwdl&sr=c

Creates this storage_uri:
(gdb) p /s sas_URI
$2 = {m_primary_uri = {m_uri = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
        _M_p = 0x89a9d8 "http://sdl18042.labs.teradata.com:10000/devstoreaccount1?api-version=2016-05-31&se=2018-04-20T16%3A22%3A29Z&si=containerSASPolicy&sig=%2FCxP8SaeL23NZYE8WyJzQ08HteAgFNt0Essiec40ZRg%3D&sp=racwdl&spr=htt"...}}, 
    m_components = {m_scheme = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x899018 "http"}}, m_host = {static npos = <optimized out>, 
        _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x898788 "sdl18042.labs.teradata.com"}}, m_user_info = {static npos = <optimized out>, 
        _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7ffff2a61fb8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_path = {static npos = <optimized out>, 
        _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x89b358 "/devstoreaccount1"}}, m_query = {static npos = <optimized out>, 
        _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
          _M_p = 0x89abf8 "api-version=2016-05-31&se=2018-04-20T16%3A22%3A29Z&si=containerSASPolicy&sig=%2FCxP8SaeL23NZYE8WyJzQ08HteAgFNt0Essiec40ZRg%3D&sp=racwdl&spr=https%2Chttp&sr=c&sv=2016-05-31"}}, m_fragment = {
        static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7ffff2a61fb8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_port = 10000}}, 
  m_secondary_uri = {m_uri = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x898dd8 "/"}}, m_components = {m_scheme = {
        static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7ffff2a61fb8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_host = {
        static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7ffff2a61fb8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_user_info = {
        static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7ffff2a61fb8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_path = {
        static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x89c858 "/"}}, m_query = {static npos = <optimized out>, 
        _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7ffff2a61fb8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_fragment = {static npos = <optimized out>, 
        _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7ffff2a61fb8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_port = -1}}}
(gdb) 

Using these storage_credentails:
(gdb) p /s sasCreds
$3 = {m_sas_token = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
      _M_p = 0x899f28 "sv=2016-05-31&si=containerSASPolicy&sig=%2FCxP8SaeL23NZYE8WyJzQ08HteAgFNt0Essiec40ZRg%3D&spr=https%2Chttp&se=2018-04-20T16%3A22%3A29Z&sp=racwdl&sr=c"}}, m_sas_token_with_api_version = {static npos = <optimized out>, 
    _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
      _M_p = 0x89abf8 "api-version=2016-05-31&se=2018-04-20T16%3A22%3A29Z&si=containerSASPolicy&sig=%2FCxP8SaeL23NZYE8WyJzQ08HteAgFNt0Essiec40ZRg%3D&sp=racwdl&spr=https%2Chttp&sr=c&sv=2016-05-31"}}, m_account_name = {
    static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7ffff2a61fb8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, 
  m_account_key = {<std::_Vector_base<unsigned char, std::allocator<unsigned char> >> = {_M_impl = {<std::allocator<unsigned char>> = {<__gnu_cxx::new_allocator<unsigned char>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, 
        _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}}
(gdb)

**Comment by katmsft** [comment]
Hi, thanks for reporting the issue.

The error indicates that you have multiple credentials used for the initialization. The code below can resolve the issue.

```
utility::string_t sasToken = create_container_shared_policy(container);
ucout << U("<<< SAS Service Token >>> ") << sasToken << std::endl;

storage_credentials sasCreds = storage_credentials(sasToken);

web::http::uri primaryaccountURI = accountURI.primary_uri();
//web::http::uri secondaryaccountURI = accountURI.secondary_uri();

// web::http::uri sasprimaryURI = sasCreds.transform_uri(primaryaccountURI);
//Instantiate a SAS based instance of the storage_uri
storage_uri sas_URI = storage_uri(primaryaccountURI);

cloud_block_blob block_blob = cloud_block_blob(sas_URI, sasCreds);
```

**Comment by vinjiang** [comment]
Please let us know if you still have questions.
