### ISSUE TITLE
azure::storage::cloud_table::execute() doesn't return

### ISSUE THREAD

**Issue by krypto92** [Azure/azure-storage-cpp#170]
I have an issue with Azure storage table library (using with cosmos table). The call "azure::storage::cloud_table::execute" hangs and will never return.

Here is my code,

`#include <was/storage_account.h>
#include <was/table.h>

int main() {
    azure::storage::cloud_storage_account storage_account = azure::storage::cloud_storage_account::parse("<connection_string>");
    azure::storage::cloud_table_client table_client = storage_account.create_cloud_table_client();
    azure::storage::cloud_table table = table_client.get_table_reference("test"); // table already created
    azure::storage::table_operation retrieve_operation = 
    azure::storage::table_operation::retrieve_entity("partition_key", "row_key");
    azure::storage::table_result retrieve_result = table.execute(retrieve_operation);
    azure::storage::table_entity entity = retrieve_result.entity();
    const azure::storage::table_entity::properties_type& properties = entity.properties();
    // fetch value from properties
    return 0;
}`

But the strange behavior is when i run the above code as standalone it works fine but it was not working after integrating with my application (Apache httpd). here is the stack trace,

`#0  0x00007f19666c0945 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007f1962043a6c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () at /lib64/libstdc++.so.6
#2  0x00007f19656f6273 in std::condition_variable::wait<pplx::details::event_impl::wait(unsigned int)::{lambda()#1}>(std::unique_lock<std::mutex>&, pplx::details::event_impl::wait(unsigned int)::{lambda()#1}) (this=0x7f192c11d4e0, __lock=..., __p=...) at /usr/include/c++/4.8.2/condition_variable:93
#3  0x00007f19656f4ad0 in pplx::details::event_impl::wait(unsigned int) (this=0x7f192c11d4b8, timeout=4294967295) at /3rdparty_deps/cpprestsdk/Release/include/pplx/pplxlinux.h:105
#4  0x00007f19656f4b97 in pplx::details::event_impl::wait() (this=0x7f192c11d4b8) at /3rdparty_deps/cpprestsdk/Release/include/pplx/pplxlinux.h:121
#5  0x00007f19656f4e18 in pplx::details::_TaskCollectionImpl::_Wait() (this=0x7f192c11d4b8) at /3rdparty_deps/cpprestsdk/Release/include/pplx/pplx.h:170
#6  0x00007f19656f4dfe in pplx::details::_TaskCollectionImpl::_RunAndWait() (this=0x7f192c11d4b8) at /3rdparty_deps/cpprestsdk/Release/include/pplx/pplx.h:165
#7  0x00007f19656f502d in pplx::details::_Task_impl_base::_Wait() (this=0x7f192c11d458) at /3rdparty_deps/cpprestsdk/Release/include/pplx/pplxtasks.h:1766
#8  0x00007f19656f6cd8 in pplx::task<azure::storage::table_result>::get() const (this=0x7f194bd79970) at /3rdparty_deps/cpprestsdk/Release/include/pplx/pplxtasks.h:3570
#9  0x00007f19656f5c16 in azure::storage::cloud_table::execute(azure::storage::table_operation const&) const (this=0x9cdd08, operation=...) at /3rdparty_deps/azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/was/table.h:2015
#10 0x00007f19656f41ef in CosmosTable::findKeyGen(unsigned short, std::string const&, std::string&) (this=0x9cda40, family=0, key="url_normalize", value="") at CosmosTable.cpp:33`

**Comment by katmsft** [comment]
Hi @krypto92 , thanks for reporting the issue. Can you confirm that this issue also persist when you run against Azure Storage Table service?

**Comment by krypto92** [comment]
@katmsft yes this issue persists in azure table storage table also.

**Comment by katmsft** [comment]
This issue is to be closed due to long time now response. Please feel free to contact us again or reopen the issue if this issue persist.
