### ISSUE TITLE
Q: why every sample waits for streams to close after blocking operations?

### ISSUE THREAD

**Issue by crusader-mike** [Azure/azure-storage-cpp#181]
Every code sample I've seen does smth along these lines:
```
auto image_stream = concurrency::streams::file_stream<uint8_t>::open_istream(image_file).get();
block_blob.upload_from_stream(image_stream);  <--- blocks until completion
image_stream.close().wait();                  <---- why?
```

What is the point of blocking until unused stream is closed?

**Comment by JasonYang-MSFT** [comment]
image_stream.close() returns an async task, it is better to make sure the close is finished.

It is not required to wait here. If you want, you can wait later or just check the close task is finished or not.

**Comment by crusader-mike** [comment]
I see... Thank you
