### ISSUE TITLE
How to send logging from console to a file or /var/log/messages

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-storage-cpp#182]
Hi,

This is rather a C++ REST API question I guess but from azure sdk prospective, how do I redirect the console logging to somewhere else?

Thanks so much in advance,

Yang

**Comment by JasonYang-MSFT** [comment]
@yxiang92128 , I will assume you are using linux because of "/var/log/messages" you provided.

If you are talking about the logging info in our sdk, Here is a related issue on logging. #168 

`boost::log::add_file_log` is the function you can use to output the logs to a file.

**Comment by vinjiang** [comment]
Feel free to let us know if you have further questions on this.
