### ISSUE TITLE
installing to lib64

### ISSUE THREAD

**Issue by crusader-mike** [Azure/azure-storage-cpp#183]
It would be really nice if azure-storage-cpp's CMakeLists.txt allowed be to override lib installation directory on x64 systems. Something like -DCMAKE_INSTALL_LIBDIR=lib64. Moving files manually after `make install` is PITA.

**Comment by JasonYang-MSFT** [comment]
@crusader-mike , Thanks for reaching out. Let's see whether we can make it to next release. Also if you want, you can contribute the repo.

**Comment by crusader-mike** [comment]
Alas, I am not particularly familiar with CMake :-\

**Comment by katmsft** [comment]
This issue is addressed in 5.0.0, feel free to try it!

**Comment by crusader-mike** [comment]
Thanks!
