### ISSUE TITLE
Q: library initialization

### ISSUE THREAD

**Issue by crusader-mike** [Azure/azure-storage-cpp#184]
Does azure-storage-cpp require explicit initialization step? 

If yes -- which one and when?

If no -- why? I know for a fact that openssl (that this library depends on on Linux) requires it and it's initialization isn't thread-safe -- i.e. if azure-storage-cpp does it on my behalf, it'll race with openssl initialization executed elsewhere in my code.

**Comment by JasonYang-MSFT** [comment]
Link the issue to https://github.com/Microsoft/cpprestsdk/issues/760

**Comment by crusader-mike** [comment]
If you explicitly un-initialize OpenSSL (or uses a library that does) -- then yes, you need to initialize it before using azure-storage-cpp. Unfortunately boost.asio (used by cpprestdsdk, used by azure-storage-cpp) requires OpenSSL and initializes it in global scope. Which means when you uninitialize it -- you break boost.asio's expectations.
