### ISSUE TITLE
Maximizing reading rate

### ISSUE THREAD

**Issue by irine-k** [Azure/azure-storage-cpp#188]
I have an application that reads 15K data blocks from Azure storage with maximal rate:
`	azure::storage::cloud_block_blob blob = get_block_blob_reference(blobName);
	return blob.download_range_to_stream_async(target, offsetBytes, sizeBytes);` 

The goal is to reach maximal possible reading rate. The application reaches about 55 MB/sec throughput with single process, while running **on the same machine** (16 cores) with 2 processes, I got total throughput > 80 MB/sec.
![c16-w2-c900](https://user-images.githubusercontent.com/39879883/40890443-cf7e3e94-677e-11e8-843c-a907bfa7cc82.JPG)
![c16-w3-c900-double_proc](https://user-images.githubusercontent.com/39879883/40890446-d7bc0ec4-677e-11e8-8f9a-2391d52d3e18.JPG)

  I tried to increase the number of threads in Casablanca code following MS support advice, doubled the number of threads here:

`threadpool& threadpool::shared_instance()
{
    static threadpool_impl s_shared(40);
    return s_shared;
}
` 

But didn't see any effect on reading rate. The number of threads created by the process varies between ~150 to ~450 independent of the number of threads initiated by the threadpool.
Any ideas how to increase reading rate/request concurrency?

**Comment by JasonYang-MSFT** [comment]
Hi @irine-k,
`blob.download_range_to_stream_async(target, offsetBytes, sizeBytes)
`
will have only one http connection to do sequential download. 

Here is a test case to enable parallel download: https://github.com/Azure/azure-storage-cpp/blob/98fca4add97d6bee26f091b69cacf07ccf25a0c6/Microsoft.WindowsAzure.Storage/tests/cloud_blob_test.cpp#L744.

**Comment by irine-k** [comment]
According to documentation: 
"void azure::storage::blob_request_options::set_parallelism_factor(int 	value)	
Sets the number of blocks or pages that may be simultaneously uploaded or downloaded when uploading or downloading a blob that is greater than the value specified by the single_blob_upload_threshold_in_bytes property in size."

In my case single_blob_upload_threshold_in_bytes is 32M and blob size is 15K. Is setting of parallelism factor applicable in my case?

**Comment by vinjiang** [comment]
Please don't hesitate to let us know if you need further assistance.
