### ISSUE TITLE
Bug: set_value doesn't set binary property type

### ISSUE THREAD

**Issue by smlu** [Azure/azure-storage-cpp#193]
When adding binary value to class ```entity_property``` via member function ```set_value``` the function doesn't set property type as binary and also it doesn't mark property as not null. This leads to an exception being thrown when calling member function ```binary_value``` because property is marked as string type.

The resolution for this bug is straightforward. I can provide the fix via pull request.
Ref: [table.h#L578](https://github.com/Azure/azure-storage-cpp/blob/master/Microsoft.WindowsAzure.Storage/includes/was/table.h#L578)

**Comment by katmsft** [comment]
Hi, thanks for reporting the issue.

It seems to be a day 0 bug, the fix is straight forward but it will be best if you could add some test as well, if you would like to send a pull request.

**Comment by katmsft** [comment]
Hi, this issue is resolved in 5.1.0. Please take a look.

**Comment by smlu** [comment]
Thank you, I'm closing this issue.
