### ISSUE TITLE
Blob batch download?

### ISSUE THREAD

**Issue by AFFogarty** [Azure/azure-storage-cpp#207]
Hello,

Are there any plans to add support for batch download of blobs? This feature would be very useful for our scenarios.

Thanks,

Andrew

**Comment by JasonYang-MSFT** [comment]
By saying 'batch download', do you mean submit a list of blob names in one request or submit download jobs then download in the background?

Can you drop us an email about you detail scenarios? 

Thanks,
-Jason

**Comment by vinjiang** [comment]
Feel free to let us know if you need further assistance on this topic.
