### ISSUE TITLE
Can't compile v5.1.0 or master

### ISSUE THREAD

**Issue by badc0re** [Azure/azure-storage-cpp#209]
I have managed to compile the project release version v5.0.0, but not the latest released version. I am using Ubuntu 16.04.

Make file details:

> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   log
> --   log_setup
> --   random
> --   system
> --   thread
> --   locale
> --   regex
> --   filesystem
> --   chrono
> --   date_time
> --   atomic
> -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.0.2g", minimum required is "1.0.0") 
> -- Found UUID : /usr/lib/x86_64-linux-gnu/libuuid.so
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
> -- Found CASABLANCA  : /usr/lib/x86_64-linux-gnu/libcpprest.so
> -- Found LibXML2: /usr/lib/x86_64-linux-gnu/libxml2.so  
> -- Setting gcc options
> -- Configuring done
> -- Generating done

Error Message:

> Scanning dependencies of target azurestorage
> [  1%] Building CXX object src/CMakeFiles/azurestorage.dir/xml_wrapper.cpp.o
> [  3%] Building CXX object src/CMakeFiles/azurestorage.dir/xmlhelpers.cpp.o
> [  5%] Building CXX object src/CMakeFiles/azurestorage.dir/response_parsers.cpp.o
> In file included from /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/includes/wascore/protocol.h:25:0,
>                  from /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:19:
> /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h: In static member function ‘static pplx::task<void> azure::storage::core::executor_impl::execute_async(s
> td::shared_ptr<azure::storage::core::storage_command_base>, const azure::storage::request_options&, azure::storage::operation_context)’:
> /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h:370:20: error: ‘_do_while’ is not a member of ‘pplx::details’
>              return pplx::details::_do_while([instance]() -> pplx::task<bool>
>                     ^
> /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp: In function ‘std::chrono::seconds azure::storage::protocol::parse_lease_time(const web::http::http_respons
> e&)’:
> /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:162:53: error: ‘utility::conversions::details’ has not been declared
>              int64_t seconds = utility::conversions::details::scan_string<int64_t>(value);
>                                                      ^
> /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:162:81: error: expected primary-expression before ‘>’ token
>              int64_t seconds = utility::conversions::details::scan_string<int64_t>(value);
>                                                                                  ^
> /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp: In function ‘int azure::storage::protocol::parse_approximate_messages_count(const web::http::http_response
> &)’:
> /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:176:42: error: ‘utility::conversions::details’ has not been declared
>              return utility::conversions::details::scan_string<int>(value);
>                                           ^
> /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:176:63: error: expected primary-expression before ‘int’
>              return utility::conversions::details::scan_string<int>(value);
>                                                                ^
> /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:176:63: error: expected ‘;’ before ‘int’
> /home/mypc/development/useful_scripts/blob_storage_cpp/azure-storage-cpp-5.1.0/Microsoft.WindowsAzure.Storage/src/response_parsers.cpp:176:66: error: expected unqualified-id before ‘>’ token
>              return utility::conversions::details::scan_string<int>(value);
>                                                                   ^
> src/CMakeFiles/azurestorage.dir/build.make:110: recipe for target 'src/CMakeFiles/azurestorage.dir/response_parsers.cpp.o' failed
> make[2]: *** [src/CMakeFiles/azurestorage.dir/response_parsers.cpp.o] Error 1
> CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/azurestorage.dir/all' failed
> make[1]: *** [src/CMakeFiles/azurestorage.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by katmsft** [comment]
It seems that you are still using Casablanca 2.9.1. For 5.1.0 or later versions, Casablanca 2.10.3+ version must be used.

**Comment by vinjiang** [comment]
Please let us know if you still have questions.

**Comment by neelam256** [comment]
I am still getting same issue, I tried with Casablanca 2.8.0-2 ( ubuntu 16.04) and   Casablanca  2.10.2 (ubuntu 18.x) and and azure-storage-cpp is 7.1.0 and 7.2.0
@vinjiang  @badc0re @katmsft

**Comment by JinmingHu-MSFT** [comment]
@neelam256 Hi, please follow the instructions on home page of this repo. Casablanca 2.10.14 is recommended for azure-storage-cpp 7.0.0 and above.
