### ISSUE TITLE
Flags for static library?

### ISSUE THREAD

**Issue by badc0re** [Azure/azure-storage-cpp#211]
I want to instead create a .a file instead of shared object, I have used -DBUILD_SHARED_LIBS=0 tag for it, but I have errors when linking it

> libazurestorage.a(xml_wrapper.cpp.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC

Any hints?

**Comment by JasonYang-MSFT** [comment]
@badc0re , which sdk version and OS version are you using?

**Comment by badc0re** [comment]
16.04 with 5.0.0 SDK version.

**Comment by JasonYang-MSFT** [comment]
I just tried same environment, it worked. Can you try a clean build?

HEAD is now at 76cb553... Version change to 5.0.0, and dropped Nuget package with name 'wastorage'
root@ea0cd4f161fe:~/azure-storage-cpp/Microsoft.WindowsAzure.Storage/build.release# make -j 4
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   log
--   log_setup
--   random
--   system
--   thread
--   locale
--   regex
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found UUID : /usr/lib/x86_64-linux-gnu/libuuid.so
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Found CASABLANCA  : /root/casablanca/Release/build.release/Binaries/libcpprest.so
-- Setting gcc options
-- Configuring done
-- Generating done
-- Build files have been written to: /root/azure-storage-cpp/Microsoft.WindowsAzure.Storage/build.release
Scanning dependencies of target azurestorage
[  3%] Building CXX object src/CMakeFiles/azurestorage.dir/xmlhelpers.cpp.o
[  3%] Building CXX object src/CMakeFiles/azurestorage.dir/request_result.cpp.o
[  5%] Building CXX object src/CMakeFiles/azurestorage.dir/response_parsers.cpp.o
[  7%] Building CXX object src/CMakeFiles/azurestorage.dir/request_factory.cpp.o
[  9%] Building CXX object src/CMakeFiles/azurestorage.dir/protocol_xml.cpp.o
[ 10%] Building CXX object src/CMakeFiles/azurestorage.dir/navigation.cpp.o
[ 12%] Building CXX object src/CMakeFiles/azurestorage.dir/async_semaphore.cpp.o
[ 14%] Building CXX object src/CMakeFiles/azurestorage.dir/util.cpp.o
[ 16%] Building CXX object src/CMakeFiles/azurestorage.dir/table_request_factory.cpp.o
[ 18%] Building CXX object src/CMakeFiles/azurestorage.dir/table_response_parsers.cpp.o
[ 20%] Building CXX object src/CMakeFiles/azurestorage.dir/table_query.cpp.o
[ 21%] Building CXX object src/CMakeFiles/azurestorage.dir/entity_property.cpp.o
[ 23%] Building CXX object src/CMakeFiles/azurestorage.dir/shared_access_signature.cpp.o
[ 25%] Building CXX object src/CMakeFiles/azurestorage.dir/retry_policies.cpp.o
[ 27%] Building CXX object src/CMakeFiles/azurestorage.dir/resources.cpp.o
[ 29%] Building CXX object src/CMakeFiles/azurestorage.dir/queue_request_factory.cpp.o
[ 30%] Building CXX object src/CMakeFiles/azurestorage.dir/file_request_factory.cpp.o
[ 32%] Building CXX object src/CMakeFiles/azurestorage.dir/file_response_parsers.cpp.o
[ 34%] Building CXX object src/CMakeFiles/azurestorage.dir/protocol_json.cpp.o
[ 36%] Building CXX object src/CMakeFiles/azurestorage.dir/operation_context.cpp.o
[ 38%] Building CXX object src/CMakeFiles/azurestorage.dir/mime_multipart_helper.cpp.o
[ 40%] Building CXX object src/CMakeFiles/azurestorage.dir/logging.cpp.o
[ 41%] Building CXX object src/CMakeFiles/azurestorage.dir/hashing.cpp.o
[ 43%] Building CXX object src/CMakeFiles/azurestorage.dir/constants.cpp.o
[ 45%] Building CXX object src/CMakeFiles/azurestorage.dir/streams.cpp.o
[ 47%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_file_ostreambuf.cpp.o
[ 49%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_file.cpp.o
[ 50%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_file_directory.cpp.o
[ 52%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_file_share.cpp.o
[ 54%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_file_client.cpp.o
[ 56%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_table_client.cpp.o
[ 58%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_table.cpp.o
[ 60%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_storage_account.cpp.o
[ 61%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_queue_message.cpp.o
[ 63%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_queue_client.cpp.o
[ 65%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_queue.cpp.o
[ 67%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_page_blob.cpp.o
[ 69%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_core.cpp.o
[ 70%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_client.cpp.o
[ 72%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_block_blob.cpp.o
[ 74%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_blob_directory.cpp.o
[ 76%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_blob_container.cpp.o
[ 78%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_blob_shared.cpp.o
[ 80%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_blob_ostreambuf.cpp.o
[ 81%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_blob_istreambuf.cpp.o
[ 83%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_blob_client.cpp.o
[ 85%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_blob.cpp.o
[ 87%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_append_blob.cpp.o
[ 89%] Building CXX object src/CMakeFiles/azurestorage.dir/blob_response_parsers.cpp.o
[ 90%] Building CXX object src/CMakeFiles/azurestorage.dir/blob_request_factory.cpp.o
[ 92%] Building CXX object src/CMakeFiles/azurestorage.dir/basic_types.cpp.o
[ 94%] Building CXX object src/CMakeFiles/azurestorage.dir/authentication.cpp.o
[ 96%] Building CXX object src/CMakeFiles/azurestorage.dir/cloud_common.cpp.o
[ 98%] Linking CXX static library ../Binaries/libazurestorage.a
[100%] Built target azurestorage

**Comment by vinjiang** [comment]
Feel free to let us know if you have further questions on this.
