### ISSUE TITLE
Add an option in CMake to build azure-storage-cpp using /MT

### ISSUE THREAD

**Issue by howryu** [Azure/azure-storage-cpp#220]
I am building azure-storage-cpp by myself on widows using cmake. Right now it worked as excepted that by default cmake is built with /MD option. It would be better to have an option to build with /MT. I know I can use vcpkg, but I am more comfortable with building the package by myself.

I had the same problem on cpprestsdk, I opened an issue in https://github.com/Microsoft/cpprestsdk/issues/881

**Comment by JasonYang-MSFT** [comment]
Sorry for the late reply, we are on vacation because of Chinese National Day holidays.

Changing /MD to /MT also requires code changes

**Comment by katmsft** [comment]
This is supported in 6.0.0
