### ISSUE TITLE
how to use set_ssl_context_callback() function

### ISSUE THREAD

**Issue by zhuweili** [Azure/azure-storage-cpp#229]
Currently I am using blob to upload some file to azure. 
I need to use my own .pem file, end up with set_ssl_context_callback() function.
Can I get a code example about how to and where to use this function during creating client?
I can't find any docs about this. 
Thanks.

**Comment by katmsft** [comment]
Please take a look at this issue: https://github.com/Azure/azure-storage-cpp/issues/197
