### ISSUE TITLE
Visual Studio 2010 support

### ISSUE THREAD

**Issue by thanhdowisc** [Azure/azure-storage-cpp#24]
Hi,

Does the current release support VC 2010? We have a strong interest in building and running this under VC10 for legacy reason.

Thanks

**Comment by slepox** [comment]
@thanhdowisc, thanks for the interest.  We have not tested this SDK on VS2010, but only the latest two versions of Visual Studio – VS2013 and VS2012. That being said, as the source code is available, you can fork this repository and try it with VS2010 if you wish.  Note that the Storage SDK depends on the C++ REST SDK, which also does not support VS 2010 either.
