### ISSUE TITLE
Choose which part of a blob to download

### ISSUE THREAD

**Issue by johnBuffer** [Azure/azure-storage-cpp#246]
Hello,

I am trying to implement a full streaming FUSE based filesystem (by _full streaming_ I mean no use of disk storage as cache) over Azure Blob storage. 

In the documentation I found this method to download a blob: 

```cpp
// Save blob contents to a file.
concurrency::streams::container_buffer<std::vector<uint8_t>> buffer;
concurrency::streams::ostream output_stream(buffer);
blockBlob.download_to_stream(output_stream);
```

But I am wondering how would it be possible to integrate this into the read function of a filesystem to download only the needed part of the blob ?

Thank you

**Comment by katmsft** [comment]
Hi,

You can try call `azure::storage::blob::open_read` instead, it will return an `concurrency::streams::istream` that can be used to read on demand.

Also, `azure::storage::blob::download_range_to_stream` can specify the range that gets downloaded to stream.

**Comment by johnBuffer** [comment]
Thank you very much for your answer ! I will try these two options.

**Comment by johnBuffer** [comment]
It is exactly what I needed, thank you very much.

**Comment by katmsft** [comment]
Also, there is a current library implementing fuse with block blob:
https://github.com/Azure/azure-storage-fuse
The underneath API calling Azure Storage services is using another lightweight version of this SDK that can be found below:
https://github.com/Azure/azure-storage-cpplite
