### ISSUE TITLE
DNS caching in sdk

### ISSUE THREAD

**Issue by lsong0905** [Azure/azure-storage-cpp#267]
Hello, 
I am trying to run some testing that modifies DNS caching timeout value, and wondering if DNS entries are cached in sdk (If so, would you please explain where). And, I am also wondering if it is by default honoring the TTL value.

**Comment by katmsft** [comment]
It is managed by operating system. However since the connections are reused at lower end, the DNS entries can be preserved from one request to another, this needs to be further confirmed.

**Comment by lsong0905** [comment]
@katmsft Thank you for the reply. So there may be connection caching in the lower layer of sdk. When it does, I want to see for how long the cache is alive. Another question is how DNS name resolution is currently done? I am still digging into how DNS resolution and managing connections work, and I would appreciate if you can advise where I should take a look to understand that.

**Comment by JinmingHu-MSFT** [comment]
The DNS and HTTP(S) stuff is handled by underlaying cpprestsdk library, and maybe further handled by its dependencies or by other applications or OS. How it works maybe different from one platform to another. But azure-storage-cpp doesn't do anything about this.

**Comment by lsong0905** [comment]
@JinmingHu-MSFT Thank you for the reply. You may close this question.
