### ISSUE TITLE
Any plan to fix the typo next_visibile_time in class cloud_queue_message?

### ISSUE THREAD

**Issue by kaifengz** [Azure/azure-storage-cpp#268]
https://github.com/Azure/azure-storage-cpp/blob/91878b1c67799f85cb2bd6af36684b043f4651ce/Microsoft.WindowsAzure.Storage/includes/was/queue.h#L293

**Comment by katmsft** [comment]
Although it is valid and the change is relatively small, it is a breaking change that all customers have to adapt to if applied. Considering this the change will be made next time when there is another breaking change to be applied to this repository. Thanks for reporting the issue.

**Comment by JinmingHu-MSFT** [comment]
Fixed in Release 7.0.0
