### ISSUE TITLE
Linking in Debug fails due to missing "-lgcov"

### ISSUE THREAD

**Issue by crusader-mike** [Azure/azure-storage-cpp#272]
[This line](https://github.com/Azure/azure-storage-cpp/blob/b00cc6788dc6f09088fe97a3c3bde86d4d52ccf5/Microsoft.WindowsAzure.Storage/src/CMakeLists.txt#L67) creates `gcov` dependency in Debug build. Unfortunately this dependency is not declared later. 

This leads to linking errors in debug build of final executable. (In my case `azure-storage-cpp` is built as static lib (on Linux) via vcpkg).

**Comment by JinmingHu-MSFT** [comment]
Hi, I'm investigating this issue.
I just tried to build both debug and release static lib on Ubuntu 18.04, and everything works just fine.
So can you provide detailed build environment, Linux distribution and version, GCC version, etc, so that I can reproduce this issue?

**Comment by crusader-mike** [comment]
@JinmingHu-MSFT Yes, static lib builds fine. But if you try to build an executable (that links this static lib) -- link stage will fail with bunch of messages like this:
```
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(retry_policies.cpp.o): In function `_GLOBAL__sub_I_00100_0_retry_policies.cpp':
/home/user/vcpkg/buildtrees/azure-storage-cpp/src/v6.0.0-352a3c139d/Microsoft.WindowsAzure.Storage/src/retry_policies.cpp:157: undefined reference to `__gcov_init'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(retry_policies.cpp.o): In function `_GLOBAL__sub_D_00100_1_retry_policies.cpp':
/home/user/vcpkg/buildtrees/azure-storage-cpp/src/v6.0.0-352a3c139d/Microsoft.WindowsAzure.Storage/src/retry_policies.cpp:157: undefined reference to `__gcov_exit'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(retry_policies.cpp.o):(.data.rel+0x40): undefined reference to `__gcov_merge_add'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(operation_context.cpp.o): In function `_GLOBAL__sub_I_00100_0_operation_context.cpp':
/home/user/vcpkg/buildtrees/azure-storage-cpp/src/v6.0.0-352a3c139d/Microsoft.WindowsAzure.Storage/src/operation_context.cpp:55: undefined reference to `__gcov_init'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(operation_context.cpp.o): In function `_GLOBAL__sub_D_00100_1_operation_context.cpp':
/home/user/vcpkg/buildtrees/azure-storage-cpp/src/v6.0.0-352a3c139d/Microsoft.WindowsAzure.Storage/src/operation_context.cpp:55: undefined reference to `__gcov_exit'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(operation_context.cpp.o):(.data.rel+0x40): undefined reference to `__gcov_merge_add'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(cloud_core.cpp.o): In function `_GLOBAL__sub_I_00100_0_cloud_core.cpp':
/home/user/vcpkg/buildtrees/azure-storage-cpp/src/v6.0.0-352a3c139d/Microsoft.WindowsAzure.Storage/src/cloud_core.cpp:98: undefined reference to `__gcov_init'
```

I assume this is because `gcov` dependency isn't mentioned anywhere in CMakeLists.txt. But I could be wrong -- not sure how I am supposed to deal with code coverage stuff.

**Comment by JinmingHu-MSFT** [comment]
As far as I know, you'll need to add the linker flag `-lgcov` anyway. There is nothing we can do during build of the static library, to eliminate the `-lgcov` flag when linking the final executable.

Another way to do this is our azure-storage-cpp sdk provides a ProjectConfig.cmake file and takes care of all these link stuff in this CMake file, so that you can use something like `find_package(AzureStorageCpp)` in your final executable CMake file. But unfortunately, we don't provide this for the present.

**Comment by crusader-mike** [comment]
I see... Well, one way would be to remove `-fprofile-arcs -ftest-coverage` in debug build. Why do you really need it? How about adding it only if some CMake variable is ON (i.e. make it conditional and off by default)? Or use CMake support for code coverage as explained [here](https://stackoverflow.com/questions/13116488/detailed-guide-on-using-gcov-with-cmake-cdash)...

In any case it would be nice to add `AzureStorageCpp` CMake module (i.e. to enable `find_package`).

**Comment by crusader-mike** [comment]
In any case, in vcpkg I resorted to removing `-fprofile-arcs -ftest-coverage` via patch. See Microsoft/vcpkg#7311
