### ISSUE TITLE
error C4172: returning address of local variable or temporary

### ISSUE THREAD

**Issue by CloudyMcFox** [Azure/azure-storage-cpp#275]
cloud_core.cpp::get_wastorage_ambient_scheduler is returning a ref to a temporary because pplx::get_ambient_scheduler returns by value.

**Comment by katmsft** [comment]
This is identified as a bug and will be fixed soon.

**Comment by katmsft** [comment]
BTW, the functionality is tested, there isn't any functionality issue since compiler (VS Compiler >=1900) will optimize the behavior of returning local variable of temporary as const reference.

**Comment by JinmingHu-MSFT** [comment]
Fixed in Release 7.0.0
