### ISSUE TITLE
How is the etag for a Blob calculated?

### ISSUE THREAD

**Issue by arginite** [Azure/azure-storage-cpp#321]
Currently when I download a blob from Azure Storage I'm calculating the MD5 hash of the file to ensure that the downloaded file isn't corrupt. I would prefer to use etag, how is the etag calculated for a blob?

**Comment by JinmingHu-MSFT** [comment]
Hi @arginite , I'm not quite sure how etag is calculated. I suggest you regard it as an opaque random string. Everytime the blob's content or metadata is changed, the etag changes.
