### ISSUE TITLE
Compilation error for BlobsGettingStarted

### ISSUE THREAD

**Issue by IoTboy** [Azure/azure-storage-cpp#35]
/home/root/azure-storage-cpp/Microsoft.WindowsAzure.Storage/samples/BlobsGettingStarted/Application.cpp:104:25: error: 'class azure::storage::cloud_append_blob' has no member named 'create'
             append_blob.create();

I fixed it by replacing with append_blob.create_or_replace();

**Comment by zhimingyuan** [comment]
Thanks for reporting this issue, we have identified this issue once we released version 2.0.0, and we have made the fix in next version 2.1.0
