### ISSUE TITLE
API support for Batch Delete in SDK?  

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-storage-cpp#365]
Do we already have an API to perform batch delete as specified in the RESTapi:
https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch

Basically one request to perform a batched deletion of a list of blobs.

If not, any plan to add them soon?

Thanks,

Yang

**Comment by JinmingHu-MSFT** [comment]
@yxiang92128 We don't support blob batch in this SDK. But I happen to be working on Blob Batch feature in [Track2](https://github.com/Azure/azure-sdk-for-cpp/tree/master/sdk/storage) SDK. It will be finished in few days.

**Comment by yxiang92128** [comment]
@JinmingHu-MSFT you mean Track2 SDK will be finished in couple of days or the blob batch feature by itself?

**Comment by yxiang92128** [comment]
@JinmingHu-MSFT you mean Track2 SDK will be finished in couple of days or the blob batch feature by itself?

**Comment by JinmingHu-MSFT** [comment]
@yxiang92128 Blob batch feature.

But we already have a private release for Track2 SDK. You can have a try now if you want.

**Comment by yxiang92128** [comment]
But from the github you pointed me to, it will not be backward compatible with the current SDK. It requires a good amount of code changes?

**Comment by JinmingHu-MSFT** [comment]
it comes with new-designed API interfaces and not compatible with current Track1 SDK.

**Comment by yxiang92128** [comment]
Thanks. We will have to allocate our development effort to accommodate the change. But I've clone your github and give it a try.

Thanks,

Yang

**Comment by JinmingHu-MSFT** [comment]
> Thanks. We will have to allocate our development effort to accommodate the change. But I will clone your github and give it a try.
> 
> Thanks,
> 
> Yang

Yeah do give it a try. It resolves all known issues in Track1 SDK.

**Comment by Jinming-Hu** [comment]
Hi @yxiang92128 , blob batch is available in Track2 SDK 12.5.0.beta2. We'll ship a beta release next month.
