### ISSUE TITLE
Support for CppRestSdk?

### ISSUE THREAD

**Issue by leskodan** [Azure/azure-storage-cpp#371]
I have recently had issues with the cpprestsdk in other parts of my project and learned from the support team that it is no longer supported beyond basic maintenance to the point where I was encouraged to use curl instead. Are there plans for the cpprestsdk dependency associated with this repo to be migrated to curl? Are their any concerns with support of the cpprestsdk components in the long run?

**Comment by Jinming-Hu** [comment]
No, we're not migrating to libcurl. Actually this project will be deprecated in the future in favor of Track 2 SDK https://github.com/Azure/azure-sdk-for-cpp/tree/master/sdk/storage

**Comment by leskodan** [comment]
Got it, thanks for the reply! It was unclear to me the difference between this repo, and the one that you linked to.

**Comment by Jinming-Hu** [comment]
> It was unclear to me the difference between this repo, and the one that you linked to.

That one is our new version of storage SDK, with new-designed API, implemented based on libcurl, better performance
