### ISSUE TITLE
Readme.md needs updates

### ISSUE THREAD

**Issue by buchs** [Azure/azure-storage-cpp#38]
Was trying the unit tests procedure given there on the latest Debian distribution. I found that cmake did not like this: 

    CASABLANCA_DIR=<path to Casablanca> CXX=g++-4.8 cmake
         .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS

But it was happy when I changed to -DBUILD_TESTS=1

To actually run the unit tests the document says to use azurestoragetest, which does not exist. I couldn't even determine another file that might be its replacement.

**Comment by buchs** [comment]
Update: when I rebuilt from scratch, the second part, lack of azurestoragetest, was resolved.

**Comment by hanzhumsft** [comment]
@buchs Thanks for reporting the issue. We already fixed the first part you mentioned about README.md.
