### ISSUE TITLE
Question regarding supportability of this SDK

### ISSUE THREAD

**Issue by ajs97** [Azure/azure-storage-cpp#388]
I read in another issue - https://github.com/Azure/azure-storage-cpp/issues/382, that this SDK is going to be deprecated. I have already integrated this particular SDK in my code, I wanted to know if this SDK will still be supported (even though we might not get new features in this SDK). 

Thanks.

**Comment by Jinming-Hu** [comment]
@ajs97 We'll fix critical bugs and security issues, but we won't provide new features.
