### ISSUE TITLE
Error running build tests - do tests need updating?

### ISSUE THREAD

**Issue by buchs** [Azure/azure-storage-cpp#39]
> azure-storage-cpp/Microsoft.WindowsAzure.Storage/tests/service_properties_test.cpp:264: error: 
> Failure in blob_service_stats: Unhandled exception: Error resolving address

> azure-storage-cpp/Microsoft.WindowsAzure.Storage/tests/service_properties_test.cpp:274: error: 
> Failure in queue_service_stats: Unhandled exception: Error resolving address

> azure-storage-cpp/Microsoft.WindowsAzure.Storage/tests/service_properties_test.cpp:284: error: 
> Failure in table_service_stats: Unhandled exception: Error resolving address

Given that every other test worked, I don't see how I could have provided flawed input in the JSON file. So, I'm wondering about the test code and derived URLs. 

This is run on Debian Linux, latest release.

**Comment by buchs** [comment]
I reran the test script, and I got the same three errors, as well as (early in the test) these three errors:

> Blob:container_lease_break_infinite_period: test fixture client request ID:
> EB32D95D-27DB-43D3-8684-F56DC0159855
> azure-storage-cpp/Microsoft.WindowsAzure.Storage/tests/blob_lease_test.cpp:64: error: Failure in 
> container_lease_break_infinite_period: state == container.properties().lease_state()
> azure-storage-cpp/Microsoft.WindowsAzure.Storage/tests/blob_lease_test.cpp:67: error: Failure in 
> container_lease_break_infinite_period: status == container.properties().lease_status()
> azure-storage-cpp/Microsoft.WindowsAzure.Storage/tests/blob_lease_test.cpp:356: error: Failure 
> in container_lease_break_infinite_period: Unhandled exception: There is currently a lease on the 
> container and no lease ID was specified in the request.

Interestingly, only 4 total errors were identified in the summary count.

**Comment by sharonSilicus** [comment]
Same issue here:
~/AZURE-BLOB/azure-storage-cpp/Microsoft.WindowsAzure.Storage/build.release/Binaries$ ./samplesblobs 
Error: Error resolving address
~/AZURE-BLOB/azure-storage-cpp/Microsoft.WindowsAzure.Storage/build.release/Binaries$ ./samplesjson 
Error: Error resolving address
~/AZURE-BLOB/azure-storage-cpp/Microsoft.WindowsAzure.Storage/build.release/Binaries$ ./samplesqueues 
Error: Error resolving address

Trying on ubuntu server 14.04LTS. Every sample I try throws out this error.

**Comment by hanzhumsft** [comment]
@buchs @sharonSilicus It looks like the domain name is not correct. Can you please check your connection string?

BTW, we count errors by test cases. If all errors come from just 4 test cases, the summary would say 4 errors.
