### ISSUE TITLE
Are blob index tags supported?

### ISSUE THREAD

**Issue by crusader-mike** [Azure/azure-storage-cpp#391]
I can't find any traces of [blob index tags](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs) in the code -- are they supported?

If not -- it would be nice to support them...

**Comment by Jinming-Hu** [comment]
Blob Index isn't supported in this SDk, and we don't have plan to support it in the future.

Please switch to our [Track2 Storage C++ SDK](https://github.com/Azure/azure-sdk-for-cpp/tree/master/sdk/storage). [Blob Index](https://github.com/Azure/azure-sdk-for-cpp/blob/b4110380f03ff0e54948f6eac61e6f93f5700ced/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_service_client.hpp#L186)

**Comment by crusader-mike** [comment]
@Jinming-Hu What is "Track2 Storage C++ SDK"? And why it is better than "azure-storage-cpp"? I'd like to know what I am buying into before investing into migration...

**Comment by Jinming-Hu** [comment]
It's our next generation of storage sdk. This azure-storage-cpp sdk will be deprecated once Track2 SDK is generally available.

Track2 SDK comes with better-designed API interfaces and it's based on libcurl, so it has better performance than Track1.

**Comment by crusader-mike** [comment]
@Jinming-Hu Thank you. Does it support throttling by any chance?

**Comment by Jinming-Hu** [comment]
> @Jinming-Hu Thank you. Does it support throttling by any chance?

Nope
