### ISSUE TITLE
When will this SDK be depcrecated?

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-storage-cpp#414]
@vinjiang @Jinming-Hu 

Hi,

I hope you guys are doing okay and surviving the lockdown.

The question is when we will expect this SDK to be deprecated.  And when will "track2" be GCA?

Thanks,

Yang

**Comment by Jinming-Hu** [comment]
Hi @yxiang92128 , this SDK has already been deprecated. We won't add any new features. We only fix security issues or bugs.

The [Track2 SDK](https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/storage) is generally available for almost a year. The latest stable version until now is [12.4.0](https://github.com/Azure/azure-sdk-for-cpp/releases/tag/azure-storage-blobs_12.4.0).

May I ask what is your obstacle to migrate from the old SDK to the new one? Is there anything we can help?

**Comment by yxiang92128** [comment]
Just lack of development resources, that is all.  
Thanks for the update.
