### ISSUE TITLE
The client sends duplicated requests under high load

### ISSUE THREAD

**Issue by VitaliyMSFT** [Azure/azure-storage-cpp#42]
Hi,

Please find attached the sample cpp console app file that reproduces the issue we have recently hit in our production system. 

[ReproWAS.txt](https://github.com/Azure/azure-storage-cpp/files/49127/ReproWAS.txt)

The issue is the following: the code below invoked in parallel by ~100 threads starts producing duplicate requests after some time (from several minutes to several hours):

void CreateSegment(uint64 segmentId, const BYTE* pbBuffer, uint64 cbBufferSize, azure::storage::cloud_blob_directory& m_directory)
{
    azure::storage::cloud_append_blob appendBlob;
    try
    {
        utility::string_t blobName = utility::conversions::print_string<uint64>(segmentId);
        appendBlob = m_directory.get_append_blob_reference(blobName);

          appendBlob.create_or_replace(azure::storage::access_condition::generate_if_not_exists_condition(), m_requestOptions, m_context);

        // add header for the segment
        concurrency::streams::rawptr_buffer<BYTE> buf(pbBuffer, size_t(cbBufferSize));
        concurrency::streams::istream uploadStream = buf.create_istream();

        auto offset = appendBlob.append_block(uploadStream,
            U(""),
            azure::storage::access_condition::generate_if_append_position_equal_condition(0),
            m_requestOptions,
            m_context);

        return;
    }
    catch (const azure::storage::storage_exception& e)                                      
    {   
        ucout << U("WAS error occured: ") << e.what() << U(" error code: ") << e.result().http_status_code() << U(" blob: ") << appendBlob.name().c_str() << U(" container ") << appendBlob.container().name().c_str() << std::endl;
		//crash here
		int* crashPtr = nullptr;
		*crashPtr = 0;
    }                                                                                       
    catch (const std::exception&)                                                         
    {                                                                                       
    }                                                                                       
    catch (...)                                                                             
    {                                                                                       
    }
 
    //crash here
    int* crashPtr = nullptr;
    *crashPtr = 0;
}

After sometime, the code produces the following output:

WAS error occured: The specified blob already exists. error code: WAS error occured: The specified blob already exists. error code: 409 blob: 20/25089 container reproWAS error occured: The specified blob already exists. error code: 409 blob: 80/24960 container repro
409 blob: 60/24728 container repro
WAS error occured: The specified blob already exists. error code: 409 blob: 5/25674 container repro
WAS error occured: The specified blob already exists. error code: 409 blob: 48/24805 container repro

WAS error occured: The specified blob already exists. error code: 409 blob: 92/24718 container repro
WAS error occured: The specified blob already exists. error code: 409 blob: 56/25039 container repro
WAS error occured: The specified blob already exists. error code: 409 blob: 32/25101 container repro
WAS error occured: The specified blob already exists. error code: 409 blob: 10/25007 container repro
WAS error occured: The specified blob already exists. error code: 409 blob: 84/24287 container repro
WAS error occured: The specified blob already exists. error code: 409 blob: 52/24900 container repro
WAS error occured: The specified blob already exists. error code: 409 blob: 68/24522 container repro
WAS error occured: The append position condition specified was not met. error code: 412 blob: 28/24865 container repro
WAS error occured: The append position condition specified was not met. error code: 412 blob: 15/24753 container repro
WAS error occured: The append position condition specified was not met. error code: 412 blob: 76/24799 container repro
WAS error occured: The append position condition specified was not met. error code: 412 blob: 96/24647 container repro
WAS error occured: The append position condition specified was not met. error code: 412 blob: 44/24492 container repro
WAS error occured: The append position condition specified was not met. error code: 412 blob: 64/25010 container repro
WAS error occured: The append position condition specified was not met. error code: 412 blob: 72/25116 container repro
WAS error occured: The append position condition specified was not met. error code: 412 blob: 24/25018 container repro

Crash dumps and the project are available upon request, I couldn't attach them here as github does not support .zip files and limits the size of attached files to 10 Mb.

**Comment by sehe** [comment]
@VitaliyMSFT You left the account credentials in the sample code. I can hardly believe that was on purpose.

**Comment by VitaliyMSFT** [comment]
thanks for noticing, I've changed the account access keys.

**Comment by hanzhumsft** [comment]
@VitaliyMSFT. Thanks for reporting the issue.

The duplicated requests and 409/412 errors you met are possible in the following scenario:

1. The client send an create/append request to service.
2. Service successfully process the request and update the blob.
3. However the client never get the response from service due to some network glitch.
4. The client library will retry in this case (from your code, the default retry policy is used). Therefore, you can see the duplicated requests.
5. Because you use an access condition on if-not-exists/append-position, the second request failed with 409/412.
6. Then the create/append API will report failure.

For the purposes of experimentation, you could try to disable retries and see if you observe different failures. It’s best practice to design your system to be tolerant of such issues, for example by permitting the same block to be appended twice or by detecting access condition failure and recovering.
