### ISSUE TITLE
Use _XPLATSTR instead of U macro

### ISSUE THREAD

**Issue by chwarr** [Azure/azure-storage-cpp#45]
Are there any concerns to switching from the C++ REST SDK's `U()` macro to `_XPLATSTR()`? This will allow the storage SDK to be used in projects that define `_TURN_OFF_PLATFORM_STRING` to avoid conflicts with other uses of `U`, like as a typename after `T`.

CC: @jasonzio, @jdubrule

**Comment by jasonzio** [comment]
Yet another manifestation of "Macros are evil". If U was a free inlined function, namespace management would solve this. Meanwhile, I'm developer of neither package, and I just want to get my work done. The change I propose is very small, very simple, and very safe; it's completely invisible to users of Bond.

**Comment by chwarr** [comment]
:point_left: Poke. Anyone looking at these issues?

By the way, I have this change building (chwarr/azure-storage-cpp@d37531152bd6c2e92577b9a1bef4336875fcd14a) and can start a PR now.

**Comment by chwarr** [comment]
Can I start a PR now?

**Comment by hanzhumsft** [comment]
@chwarr Please start a PR against our dev branch. Starting from v2.3 release, this branch is for community contribution.

**Comment by chwarr** [comment]
PR #54.

**Comment by hanzhumsft** [comment]
Thanks for raising the PR. We're now evaluating it.

**Comment by hanzhumsft** [comment]
#54 merged.
