### ISSUE TITLE
visual studio 2005

### ISSUE THREAD

**Issue by itsudhiryadav** [Azure/azure-storage-cpp#48]
Does it supports visual studio 2005?
It is possible to use this library in VS 2005?
Guys please help.

**Comment by itsudhiryadav** [comment]
Guys please.

**Comment by jasonzio** [comment]
From the home page:

> Visual Studio Version
>
>Starting from version 2.1.0, Azure Storage Client Library for C++ supports Visual Studio 2013 and Visual Studio 2015. In case you have the need to use Visual Studio 2012, please get version 2.0.0.

**Comment by hanzhumsft** [comment]
This library uses lots of C++11 features, so does its dependency cpprestsdk(https://github.com/Microsoft/cpprestsdk). Therefore, Visual Studio 2012 is the least supported version.
