### ISSUE TITLE
http proxy issue

### ISSUE THREAD

**Issue by wundram** [Azure/azure-storage-cpp#5]
I didn't see this in the interface, but is there a way to set this up to have this open connections through an http proxy server?

**Comment by karataliu** [comment]
We also face the same issue on Linux, looks like we're not able to pass proxy setting for non-win environment now.
Would you consider supporting reading proxy setting from environment variables?

**Comment by hanzhumsft** [comment]
Hi, the latest release v2.3.0 has addressed this issue. Please try it.
