### ISSUE TITLE
Casablanca_DoubleJsonParsing tests sometimes fail

### ISSUE THREAD

**Issue by chwarr** [Azure/azure-storage-cpp#56]
The [Casablanca_DoubleJsonParsing](https://github.com/Azure/azure-storage-cpp/blob/4ae759a38a56b3017b21a3edbb3b06ca3ccf0774/Microsoft.WindowsAzure.Storage/tests/cloud_table_test.cpp#L2677) as of commit d37acbd sometimes fail the following assert:

```
CHECK(output_document.as_object().find(U("DoubleProperty"))->second.is_double());
```

This is because the test generates random double values, serializes them, and then parses them. However, if the generated double was 0.0 or 1.0, it ends up serialized as 0 or 1, which is no longer treated as a double after parsing.

I'm not sure how you guys want to fix this broken test case, but I'm logging this issue so that there's something about it in case anyone else runs into this problem.

**Comment by hanzhumsft** [comment]
Thanks @chwarr 

This test is actually tracking the Casablanca JSON parser behavior.  It is not testing any functionality of azure-storage-cpp. So we will leave it broken for now.
