### ISSUE TITLE
Added /usr/loca/include/UnitTest++ for centos 7 from git

### ISSUE THREAD

**Issue by heavyrecoil1974** [Azure/azure-storage-cpp#59]
I had /usr/local/include/UnitTest++ add /usr/local/lib  for the compile to work with -DBUILD_TESTS=ON:

  # find UnitTest++
  #
  # exports:
  #
  #   UnitTest++_FOUND
  #   UnitTest++_INCLUDE_DIRS
  #   UnitTest++_LIBRARIES
  #

include(FindPkgConfig)
include(FindPackageHandleStandardArgs)

  # Use pkg-config to get hints about paths
  #pkg_check_modules(UnitTest++_PKGCONF REQUIRED unittest++)
  # find UnitTest++
  #
  # exports:
  #
  #   UnitTest++_FOUND
  #   UnitTest++_INCLUDE_DIRS
  #   UnitTest++_LIBRARIES
  #

include(FindPkgConfig)
include(FindPackageHandleStandardArgs)

  # Use pkg-config to get hints about paths
  #pkg_check_modules(UnitTest++_PKGCONF REQUIRED unittest++)

  # Include dir
find_path(UnitTest++_INCLUDE_DIR
  NAMES UnitTest++.h
  PATHS
  	${UnitTest++_PKGCONF_INCLUDE_DIRS}
  	${CMAKE_SOURCE_DIR}/tests/UnitTest++/src
	/usr/local/include/UnitTest++

  # Library
find_library(UnitTest++_LIBRARY
  NAMES UnitTest++
  PATHS 
  	${UnitTest++_PKGCONF_LIBRARY_DIRS}
  	${CMAKE_SOURCE_DIR}/tests/UnitTest++
	/usr/local/lib

set(UnitTest++_PROCESS_LIBS UnitTest++_LIBRARY)
set(UnitTest++_PROCESS_INCLUDES UnitTest++_INCLUDE_DIR)
libfind_process(UnitTest++)

**Comment by hanzhumsft** [comment]
Thanks @heavyrecoil1974 for reporting the issue. We're working on a fix for it.

**Comment by hanzhumsft** [comment]
The fix is merged into dev branch.
