### ISSUE TITLE
Gert "Unhandled exception at 0x77562EEC in xxxxx.exe: Microsoft C++ exception: std::runtime_error at memory location 0x0107B60C." error

### ISSUE THREAD

**Issue by normalian** [Azure/azure-storage-cpp#6]
I got a error mentioned in the title when I run my own code like below.

<pre>
#include "stdafx.h"
#include "was/storage_account.h"
#include "was/table.h"
#include "was/queue.h"
#include "was/blob.h"

int _tmain(int argc, _TCHAR* argv[])
{
    // Initialize storage account
    wa::storage::cloud_storage_account storage_account = wa::storage::cloud_storage_account::parse(U("AccountName=<accoutname>;AccountKey=<account_key>;DefaultEndpointsProtocol=http;")); // the error occur in this line
</pre>

And detail error is like below

<pre>
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: C:\WINDOWS\SYSTEM32\MSVCP120D.dll
File: c:\dev12\vc\include\vector
Line: 1201

Expression: vector subscript out of range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
</pre>

**Comment by myd7349** [comment]
Hello, buddy! Have you got it fixed? 

I don't know whether it will be helpful or not. But I think you may check out your "VC++ Directories" configurations and make sure which version of `wastorage.lib` and `cpprest120(d)_2_3.lib` you are using  
For me, I linked my code with the debug(release) version of `wastorage.lib` but run the XXX.exe with the release(debug) version of `wastorage.dll` once, then I got a lot of strange unhandled exception.

**Comment by katmsft** [comment]
This issue is to be closed due to long time now response. Please feel free to contact us again or reopen the issue if this issue persist.
