### ISSUE TITLE
container.create_if_not_exists() is exceptioned,Error: WinHttpSendRequest: 12002: 鎿嶄綔瓒呮椂

### ISSUE THREAD

**Issue by pily1** [Azure/azure-storage-cpp#81]
Hi all:
    I use Microsoft.WindowsAzure.Storage.BlobsGettingStarted.v120 Samples,the code is 
      void blobs_getting_started_sample()
    {
        try
        {
            // Initialize storage account
            azure::storage::cloud_storage_account storage_account = azure::storage::cloud_storage_account::parse(storage_connection_string);

            // Create a blob container
            azure::storage::cloud_blob_client blob_client = storage_account.create_cloud_blob_client();
            //azure::storage::cloud_blob_container container = blob_client.get_container_reference(U("my-sample-container"));			
			azure::storage::cloud_blob_container container = blob_client.get_container_reference(U("test-public-blob"));
           
            // Return value is true if the container did not exist and was successfully created.
            bool bok = container.create_if_not_exists();
           // Make the blob container publicly accessible
            azure::storage::blob_container_permissions permissions;
            permissions.set_public_access(azure::storage::blob_container_public_access_type::blob);
            container.upload_permissions(permissions);
            .....
             catch (const azure::storage::storage_exception& e)
        {
            ucout << U("Error: ") << e.what() << std::endl;

            azure::storage::request_result result = e.result();
            azure::storage::storage_extended_error extended_error = result.extended_error();
            if (!extended_error.message().empty())
            {
                ucout << extended_error.message() << std::endl;
            }
        }

          when the code run "container.create_if_not_exists();",the Error is "Error: WinHttpSendRequest: 12002: 鎿嶄綔瓒呮椂",my computer is win8 x64,

**Comment by hanzhumsft** [comment]
Hi @pily1 ,

This looks an WinHTTP error, 12002 means TIMEOUT.  Can you please check whether you have the right account name and key in `SamplesCommon/samples_common.h` and the network connection to azure storage services?

**Comment by pily1** [comment]
I hava saved it ,in china ,the storage_connection_string needs to add "EndpointSuffix=core.chinacloudapi.cn"
