### ISSUE TITLE
problem listing blobs with reserved url characters

### ISSUE THREAD

**Issue by shlomiapel** [Azure/azure-storage-cpp#84]
i am trying to work with the following blob name:
ef8c1986-326c-464d-9ddb-7b9a6832740a/vm-4060/aG59()*&^#@$
i am experiencing problems creating it correctly and finding it using list.

my blob referencing code is:
`azure::storage::cloud_blob(azure::storage::storage_uri(web::uri::encode_uri(blobName)),
		azure::storage::storage_credentials(accountName,key));`

in this case, the result uri is (omitting all the beginning up to the container):
ef8c1986-326c-464d-9ddb-7b9a6832740a/vm-4060/aG59()*&%5E

for some reason, the characters "#@$" were dropped.

when listing, i am using the following in a loop according to the continuation token. 
`azure::storage::list_blob_item_segment seg =
				container.list_blobs_segmented(web::uri::encode_uri(blobName)), true, azure::storage::blob_listing_details::none,
				0, token, azure::storage::blob_request_options(),
				azure::storage::operation_context());`

Here I receive an exception due to authentication mismatch which is caused by the '&' character.
if i use encode_data_string, there is no exception but of course the blob is not found.

**Comment by JasonYang-MSFT** [comment]
@shlomiapel 
`#` is the fragment identifier in url, which lead your blob name into two parts, path and fragment.
You could try to encode uri with specifying the field.
try this to encode uri:

web::uri::encode_uri(blobName, web::uri::components::path)

A better way to get blob referencing is:
`container.get_blob_reference(blobName);`
Or if you are trying to use block blob:
`container.get_block_blob_reference(blobName);`

**Comment by shlomiapel** [comment]
i have already tried to encode the blob name using all component types and none work.
in addition the list fails to find the blob since there is an exception in case the blob name is not encoded and if encoded, the blob is not found.

**Comment by shlomiapel** [comment]
i have switched to getting the blob reference through the container and not the uri and i succeed to create a blob with the correct name but now fail to list or delete it. in both cases i get an exception caused by authentication mismatch. even if i encode the name. if i encode using encode_data_string, there is no exception but the blob is not found.
BTW, deleting the created blob is now possible only through the azure explorer. it fails in the Azure web UI as well.

**Comment by JasonYang-MSFT** [comment]
@shlomiapel 
There is a bug found in authentication while blob name contains '&'. Will send a fix in PR ASAP. Then you can merge the fix and build the sdk from source code accordingly.

BTW, the blob name seem so different to other customer. Would you like to share your scenario with us? It will be much grateful if you can send me email for a brief introduction if you want. That will help us a lot.

**Comment by JasonYang-MSFT** [comment]
@shlomiapel 
PR #85 send to fix authentication fail for blob names contain '&'.

**Comment by shlomiapel** [comment]
Thank you for the prompt update. what about using the class to refer to blobs which contain special characters in their name? i.e. using the Ctor:
WASTORAGE_API cloud_blob(storage_uri uri, storage_credentials credentials);

**Comment by shlomiapel** [comment]
regarding blob naming methodology, we create blob names which include names of VMs in our setup.
This bug happened when testing VMs with special characters in their name. This can happen in a real customer setup where they have a VM names "Finance & IT" for example or "ITServer#3", etc...

**Comment by JasonYang-MSFT** [comment]
@shlomiapel 
Thanks for your contribution.
We have released 2.4.0, this bug is fixed in this release.  You can try our newest release if you want.
