### ISSUE TITLE
corrupted while run unit tests and samples

### ISSUE THREAD

**Issue by hs79hs** [Azure/azure-storage-cpp#86]
Hi, I followed step by step instructions in README.md, "Getting Started on Linux".
Seems all is ok but when run unit tests and samples, I have the following errors:

ubuntu@ip-172-31-31-221:~/mnt/websocketpp-0.6.0/azure-storage-cpp/Microsoft.WindowsAzure.Storage/build.release/Binaries$ ./azurestoragetest
Blob:blob_lease_acquire_infinite: test fixture client request ID: 138D191D-BA95-4F84-9D2B-B99D2DB7B98B
*** Error in `./azurestoragetest': free(): corrupted unsorted chunks: 0x00007ffcd0001bf0 ***
Aborted (core dumped)

ubuntu@ip-172-31-31-221:~/mnt/websocketpp-0.6.0/azure-storage-cpp/Microsoft.WindowsAzure.Storage/build.release/Binaries$ ./samplesblobs
*** Error in `./samplesblobs': corrupted double-linked list: 0x00007fa1f4000c80 ***
Aborted (core dumped)

I run on Ubuntu 14.04.2, have installed casablanca and libboost 1.54.
Thanks for help.

**Comment by JasonYang-MSFT** [comment]
@hs79hs 
Hi, Can you share the versions of azure-storage-cpp and Casablanca?

**Comment by hs79hs** [comment]
I cloned them last weekend, by master branches, they should be the latest versions.

There are BOOST 1.54 and 1.59 on my VM, during installation, firstly I used 1.54 to make, but when run tests, it said it cannot find 1.59 libraries. Then I tried to use 1.59 to make casablanca and it failed at about 37%.
Later I used 1.54 to make and when run, I copied 1.59 libraries to /usr/lib. Then I can run unit tests and samples, but got the errors I mentioned in my last post.

Today I used a new and clean VM to install them again, only install BOOST 1.54, I can run unit tests and the result is:
FAILURE: 3 out of 252 tests failed (3 failures).

I assumes it’s ok. And when I run samples, it said,
Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

I’m sure my AccountName and Key are right because I also use them for unit tests. What are other potential reasons for this? Thanks.

**Comment by JasonYang-MSFT** [comment]
Don't worry about these 3 test failures. They are known issues about the test case. It is because sas token exceed its expiry time while running the test cases.
We fixed it in PR #87 .

**Comment by hs79hs** [comment]
Thanks, but now why I have this error while running samplesblobs:
Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**Comment by JasonYang-MSFT** [comment]
You should put your AccountName and Key in samples_common.h to enable sample codes.

Sample codes use storage credentials stored in samples_common.h: storage_connection_string, which is different from test code.

**Comment by hs79hs** [comment]
Oh, many thanks, but it's really better to add that in README
https://github.com/Azure/azure-storage-cpp/blob/master/README.md
