### ISSUE TITLE
upload_from_stream() is unable to upload large files (64MB and more) to block blob

### ISSUE THREAD

**Issue by red-9m** [Azure/azure-storage-cpp#89]
Neither upload_from_stream() nor upload_from_file() are not able to upload large files to block blob.

**Comment by jasonzio** [comment]
Maximum size of a block blob written by a single HTTP request is 64MB. Anything larger must be written as a sequence of blocks (4MB or smaller) followed by a Commit of the blocklist. Both of these APIs do a single storage operation (one big PUT); that behavior has the least impact on other scalability thresholds for the storage account (far fewer operations consumed by the upload).

I can see upload_from_file() either throwing an error if asked to upload a file larger than the one-operation limit, or switching its strategy to "upload blocks and commit a blocklist"; it's arguable that the current behavior for big files is just plain wrong.

As for upload_from_stream(), the API can't know in advance how large the stream will be; it has to choose a strategy up front. It's arguable that most streams are below the 64MB limit and so it makes sense to optimize for that case. The error handling scenarios for really large streams are complicated, and the desired behavior is generally application dependent.

**Comment by red-9m** [comment]
Python implementation of the same API has create_blob_from_path() that really changes the upload strategy depending on file size.

I propose either add support for the "sequence of blocks" strategy to upload_from_file() or create an upload_from_large_file() method, as the current C++implementation does not allow to upload larger files at all. Please consider this issue as change request, not a bug.

**Comment by JasonYang-MSFT** [comment]
@red-9m 
Currently, we will automatically swith to  "upload blocks and commit a blocklist" if
1) the stream length is known and larger than 64MB OR 2) user want to upload in parallel.
See details in:
https://github.com/Azure/azure-storage-cpp/blob/master/Microsoft.WindowsAzure.Storage/src/cloud_block_blob.cpp#L162

So, we definitely already support upload_from_file, upload_from_stream to block blob for larger files.

Can you share how you use  upload_from_file()? like which platform, versions of SDK and complier, how large the files are? Anything about those may help us resolve this issue.

**Comment by red-9m** [comment]
Linux a7 4.4.19-1-custom #1 SMP Wed Aug 24 18:57:07 EEST 2016 x86_64 GNU/Linux

**Comment by JasonYang-MSFT** [comment]
It seems the namespace error comes from XML parser. We couldn't repro this error by your sample.
Can you share your libxml version?

Also in your code, 
1)there is an extra quotation marks in connection string, might be a type error.
2) Inside try{} catch{}, container should be created before upload a file to block blob.
    try to call container.create_if_not_exists().

**Comment by red-9m** [comment]
My actual connection string doues not have extra quote. It seems to be added when I remove account key. Libxml in my system:
`pacman -Ql libxml`

    local/libxml++ 2.40.1-1
        C++ bindings to libxml2
    local/libxml2 2.9.4+0+gbdec218-2
        XML parsing library, version 2

**Comment by JasonYang-MSFT** [comment]
See in https://github.com/Azure/azure-storage-cpp/blob/master/README.md#getting-started-on-linux.
We need to build our sdk basing on libxml++ 2.6+.

**Comment by red-9m** [comment]
libxml++ 2.40.1 is newer (oct 2015). libxml++ v2.6 looks very old - may 2004. Does the trailing '+' in your "libxml++ 2.6+" means that only 2.6.0 and 2.6.1 is supported? I was unable to compile v2.6 since it has problems with latest gcc and there is no precompiled 2.6 on my distro.

**Comment by JasonYang-MSFT** [comment]
Which distro are you using?

Also, can you change to http mode in connection string and give a short network dump for us to look into this problem?

**Comment by red-9m** [comment]
I have and Arch Linux. Please find tcpdump file attached to mail send to you.

**Comment by JasonYang-MSFT** [comment]
Well received.

Are you using https mode for in this tcpdump? I can't look into the details because they are all https encrypted.

**Comment by red-9m** [comment]
Sorry for that. Just have send you http dump as well.

**Comment by JasonYang-MSFT** [comment]
Reviewed the network trace. This error should be occurred while sdk trying to call put_block_list, which depends on libxml++ to generate an xml format message. And pretty sure this works for libxml++ 2.6

The error is from libxml++ 2.4.1, see the code in:
https://github.com/GNOME/libxmlmm/blob/478a5bd59ca4e932cb3d4d43853a350b0fa76692/libxml%2B%2B/nodes/node.cc#L566

This error is disabled in libxml++2.6.0, see in:
https://github.com/GNOME/libxmlmm/blob/LIBXMLPP_2_26_0/libxml%2B%2B/nodes/node.cc#L369

You can try to modify and recompile the libxml++ 2.4.1 accordingly. This is just a suggestion based on my best guess, since I don't have the environment currently and can't repro it. 

Please share with us whether it works or not.

**Comment by red-9m** [comment]
Thanks for your time! Confirm, that commenting the line in node.cc is a workaround. I was able to upload 70Mb file with modified libxml++. However still is a question why upload of 4Mb chunks starts from 32Mb file, not from 64Mb?

**Comment by JasonYang-MSFT** [comment]
We want to better leverage the ability of parallel uploading. So we switch to put block in parallel then put block list to commit the blob from 32MB.

As a reminder, if you also want to leverage the ability of parallel uploading, you should set_parallelism_factor() in blob_options and put the option parameter in upload_from_file function. Take the sample from unit test:
https://github.com/Azure/azure-storage-cpp/blob/dev/Microsoft.WindowsAzure.Storage/tests/cloud_block_blob_test.cpp#L401

**Comment by red-9m** [comment]
Thank you very much! I close the issue now. Still hope to see a support for newer libxml++.

---
Dmitry

**Comment by JasonYang-MSFT** [comment]
Hi @red-9m,

Our newest 2.5.0 should resolve this issue, can you have a try?

**Comment by red-9m** [comment]
Hi Jason,
Just tested with all latest: azure-storage-cpp 2.5, casablanca 2.9 and libxml++ 2.40.1. Could confirm, now it works as it should, thanks!

**Comment by JasonYang-MSFT** [comment]
Hi @red-9m,

Thanks again for raise this issue and the efforts in helping us to reproduce and resolve this issue. 

Glad that we can close this issue.
