### ISSUE TITLE
Debug Assertion Expression: _pFirstBlock == pHead

### ISSUE THREAD

**Issue by kylim** [Azure/azure-storage-cpp#9]
The following assertion error is triggered after updating to version 0.3, but it does not happen with the version 0.2 build.

Debug Assertion Failed!
Program: F:\0Main\Tools\AzureTester\Debug\AzureTester.exe
File: f:\dd\vctools\crt\crtw32\misc\dbgheap.c
Line: 1424
Expression: _pFirstBlock == pHead

The code that triggers this assertion is:
azure::storage::cloud_storage_account storage_account = azure::storage::cloud_storage_account::parse(storage_connection_string);
azure::storage::cloud_table_client table_client = storage_account.create_cloud_table_client();
azure::storage::cloud_table table = table_client.get_table_reference(U("testtable"));

and the only difference between this code and the one used in 0.2 is the change in the namespace from wa::storage to azure::storage. The assertion only appears in the debug build and not in the release build, but in release build it appears to cause failures down the line that results in exceptions that do not happen when using the 0.2 build. Library was downloaded via nuget, I'm using VS2013 on x64,

**Comment by myd7349** [comment]
@MFisherMSFT Thank you! 
I encountered the same problem and got it solved according to your answer.

**Comment by watermel** [comment]
Thanks a lot.
