### ISSUE TITLE
Exception "The namespace () has not been declared." Thrown when attempting to insert message to queue

### ISSUE THREAD

**Issue by Grenite** [Azure/azure-storage-cpp#96]
I have been following the instructions for inserting queue messages (https://azure.microsoft.com/en-us/documentation/articles/storage-c-plus-plus-how-to-use-queues/) but when I attempt to insert the queue message with azure::storage::cloud_queue::add_message(some_queue_msg); the exception "The namespace () has not been declared." was thrown.

**Comment by JasonYang-MSFT** [comment]
Can you share the versions of related SDKs and the platform?

Also can you take a look at #89 , maybe they are related.

**Comment by Grenite** [comment]
casablanca version 2.8.0
azure-storage version 2.4.0.0
Linux 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
boost version 1.58
libxml++2.6-2v is at version 2.40.1-1according to typing "dpkg --list"  in bash.   
openssl is at version 1.0.2g-1ubun
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
Ubuntu 16.04 LTS "Xenial"
According to #89 the culprit appears to be using libxml version 2.40.1. However recompiling libxml seems far from ideal because I am Cross-Compiling for an ARM platform and cross-compiling packages is already adding too much down time.

**Comment by JasonYang-MSFT** [comment]
@Grenite 

I reviewed the code, it is probably caused by https://github.com/Azure/azure-storage-cpp/blob/master/Microsoft.WindowsAzure.Storage/src/xmlhelpers.cpp#L365.

While namespaceName is empty, this will throw an exception in 2.4. 

Maybe you can try to add a check to avoid namespaceName to be empty.

**Comment by Grenite** [comment]
@JasonYang-MSFT 
Does this mean I have to recompile the sdk with appropriate modifications? It would be great if you can point out where the function xml_writer::write_start_element_with_prefix is used during the use of azure::storage::cloud_queue::add_message so I can see how namespaceName is used.

**Comment by JasonYang-MSFT** [comment]
Yes, you need to recompile the sdk with modifications.

For add_message, xml_writer is used in:
https://github.com/Azure/azure-storage-cpp/blob/master/Microsoft.WindowsAzure.Storage/src/queue_request_factory.cpp#L170
Then:
https://github.com/Azure/azure-storage-cpp/blob/master/Microsoft.WindowsAzure.Storage/src/protocol_xml.cpp#L654

**Comment by Grenite** [comment]
After taking a look around in the code and testing, it seems that that I have not found any possibility for a solution, I ended up using the Function app trigger on blob function instead as a workaround.

**Comment by JasonYang-MSFT** [comment]
Hi @Grenite,

Our newest 2.5.0 should resolved this issue, can you have a try?

**Comment by Grenite** [comment]
@JasonYang-MSFT , yes I have given the 2.5.0 build a try, and I have been able to use to insert queue messages, but it seems that it is just inserting garbage text (the text looks like byte data to me) instead of the string I intend to insert.

**Comment by JasonYang-MSFT** [comment]
Hi @Grenite,

Did you get the garbage text from an e2e(insert a queue message, peek the message then compare with the original message) test?

**Comment by Grenite** [comment]
@JasonYang-MSFT, no, I received the text from checking the queue using Azure Storage Explorer application.

**Comment by JasonYang-MSFT** [comment]
@Grenite, That's wired, I just tried an e2e test according to this sample:https://azure.microsoft.com/en-us/documentation/articles/storage-c-plus-plus-how-to-use-queues/.
The text added to the queue and peeked message are equal.

Also, I downloaded an Azure Storage Explorer(Version 0.8.6) from http://download.microsoft.com/download/A/E/3/AE32C485-B62B-4437-92F7-8B6B2C48CB40/StorageExplorer.exe
The text in explorer is exactly same to the text I set through our library.

**Comment by Grenite** [comment]
@JasonYang-MSFT, it seems like it is an issue somewhere on my end, some more testing seems to reveal that inserting messages to the queue works properly.

**Comment by JasonYang-MSFT** [comment]
@Grenite ,

Thanks a lot for the confirmation.
