### ISSUE TITLE
Error with adding message / peeking message

### ISSUE THREAD

**Issue by ShahzaibGill** [Azure/azure-storage-cpp#97]
I'm able to reference the queue properly (so I can create a queue and also reference a pre-existing queue) using the sample code provided for queues on this repo. 

However, when peeking at a message or trying to add a message to the queue, the following exception is thrown:

"Error: The Uri for the target storage location is not specified. Please consider changing the request's location mode."

**Comment by JasonYang-MSFT** [comment]
Can you share the versions of this SDK, cpprestsdk, and your platform?

**Comment by JasonYang-MSFT** [comment]
@ShahzaibGill 
You might need to set you credentials in: https://github.com/Azure/azure-storage-cpp/blob/master/Microsoft.WindowsAzure.Storage/samples/SamplesCommon/samples_common.h#L25

Do you have any further questions?
